# Encuesta de Snacks Mundial FIFA 2026 (Guatemala)
**Integrantes:**
- Diego Alejandro Escobar Barahona
- Daniella Marissa Navarro Araniva
- Repositorio:https://github.com/bapatata688/soccer_world_cup_survey.git
---

### Arquitectura del proceso

```
CSV Original
    ↓
Carga con Pandas
    ↓
Exploración y diagnóstico
    ↓
Limpieza (nulos, duplicados, texto)
    ↓
Transformación de datos 
    ↓
Construcción de dimensiones y tabla Fact con el star esquema
    ↓
KPIs ejecutivos 
    ↓
Reportes para directivos
    ↓
Exportación CSV para Power BI
```

## Paso 1. Importación de librerías

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)
pd.set_option('display.float_format', '{:,.2f}'.format)

## Paso 2. Carga del CSV

In [2]:
df_raw = pd.read_csv(
    'encuesta_snacks_mundial_2026_guatemala_2500_respuestas.csv'
)

print('Dimensiones del dataset:', df_raw.shape)
df_raw.head(3)

Dimensiones del dataset: (2500, 26)

,EncuestaID,FechaEncuesta,HoraEncuesta,RangoEdad,Genero,Departamento,Municipio,Ocupacion,FrecuenciaConsumoSnacks,LugarCompraSnacks,ConQuienVePartidos,GastoSnacksPartido,SnacksSeleccionados,SaborPreferido,PresentacionPreferida,PrecioAdecuado,PagaMasEdicionMundial,PlaneaVerMundial2026,SeleccionApoya,CompraDisenoSeleccion,SeleccionInfluyeCompra,JugadoresInfluyentes,TipoPublicidadAtractiva,PromocionPreferida,CompraTarjetasColeccionables,CampaniaMasProbableCompra
0,1,2026-04-15,09:46:21,55 años o más,Femenino,Guatemala,Santa Catarina Pinula,Jubilado,Varias veces al mes,Aplicación de delivery,Amigos,Q25 - Q50,FutbolMix; Hot Stadium Peanuts; Caramel Goal P...,DULCE,Familiar,Q10 - Q15,Sí,Sí,Portugal,Probablemente sí,Portugal,Kylian Mbappé; Cristiano Ronaldo; Neymar Jr.,Una selección nacional,Sorteo de viajes,Sí,Edición Francia
1,2,2026-01-26,08:45:33,18 - 24 años,Masculino,Guatemala,Santa Catarina Pinula,Empresario,1 a 2 veces por semana,Supermercado,Solo,Q51 - Q100,ChocoKick Bites; CrunchMax BBQ,Caramelo,Familiar,Q21 - Q30,Sí,Sí,Portugal,Probablemente no,Suecia,Cristiano Ronaldo; Kylian Mbappé; Christian Pu...,Una selección nacional,Producto gratis,Sí,Edición Brasil
2,3,2026-04-22,22:23:58,35 - 44 años,Masculino,Alta Verapaz,Alta Verapaz,Estudiante,Varias veces al mes,Kiosco escolar/universitario,Familia,Q51 - Q100,ChocoKick Bites; Fan Chips Jalapeño; Victory P...,Picante Chapín,Familiar,Q16 - Q20,Sí,Sí,España,Probablemente sí,Portugal,Cristiano Ronaldo; Federico Valverde,Un jugador famoso,Descuento directo,No,Edición con tarjetas coleccionables

In [4]:
print(df_raw.columns.tolist())

['EncuestaID', 'FechaEncuesta', 'HoraEncuesta', 'RangoEdad', 'Genero', 'Departamento', 'Municipio', 'Ocupacion', 'FrecuenciaConsumoSnacks', 'LugarCompraSnacks', 'ConQuienVePartidos', 'GastoSnacksPartido', 'SnacksSeleccionados', 'SaborPreferido', 'PresentacionPreferida', 'PrecioAdecuado', 'PagaMasEdicionMundial', 'PlaneaVerMundial2026', 'SeleccionApoya', 'CompraDisenoSeleccion', 'SeleccionInfluyeCompra', 'JugadoresInfluyentes', 'TipoPublicidadAtractiva', 'PromocionPreferida', 'CompraTarjetasColeccionables', 'CampaniaMasProbableCompra']

## Paso 3. Selección de columnas — todas las secciones

Se extraen todas las columnas a utilizar

In [5]:
todas_las_columnas = [
    'EncuestaID',
    'FechaEncuesta',

    # Sección 1
    'RangoEdad',
    'Genero',
    'Departamento',
    'Municipio',
    'Ocupacion',

    # Sección 2
    'FrecuenciaConsumoSnacks',
    'LugarCompraSnacks',
    'ConQuienVePartidos',
    'GastoSnacksPartido',

    # Sección 3
    'SnacksSeleccionados',
    'SaborPreferido',
    'PresentacionPreferida',

    # Sección 4
    'PrecioAdecuado',
    'PagaMasEdicionMundial',

    # Sección 5
    'PlaneaVerMundial2026',
    'SeleccionApoya',
    'CompraDisenoSeleccion',
    'SeleccionInfluyeCompra',

    # Sección 6
    'JugadoresInfluyentes',
    'TipoPublicidadAtractiva',

    # Sección 7
    'PromocionPreferida',
    'CompraTarjetasColeccionables',
    'CampaniaMasProbableCompra'
]

df = df_raw[todas_las_columnas].copy()

print('Dimensiones del dataset unificado:', df.shape)
df.head()

Dimensiones del dataset unificado: (2500, 25)

,EncuestaID,FechaEncuesta,RangoEdad,Genero,Departamento,Municipio,Ocupacion,FrecuenciaConsumoSnacks,LugarCompraSnacks,ConQuienVePartidos,GastoSnacksPartido,SnacksSeleccionados,SaborPreferido,PresentacionPreferida,PrecioAdecuado,PagaMasEdicionMundial,PlaneaVerMundial2026,SeleccionApoya,CompraDisenoSeleccion,SeleccionInfluyeCompra,JugadoresInfluyentes,TipoPublicidadAtractiva,PromocionPreferida,CompraTarjetasColeccionables,CampaniaMasProbableCompra
0,1,2026-04-15,55 años o más,Femenino,Guatemala,Santa Catarina Pinula,Jubilado,Varias veces al mes,Aplicación de delivery,Amigos,Q25 - Q50,FutbolMix; Hot Stadium Peanuts; Caramel Goal P...,DULCE,Familiar,Q10 - Q15,Sí,Sí,Portugal,Probablemente sí,Portugal,Kylian Mbappé; Cristiano Ronaldo; Neymar Jr.,Una selección nacional,Sorteo de viajes,Sí,Edición Francia
1,2,2026-01-26,18 - 24 años,Masculino,Guatemala,Santa Catarina Pinula,Empresario,1 a 2 veces por semana,Supermercado,Solo,Q51 - Q100,ChocoKick Bites; CrunchMax BBQ,Caramelo,Familiar,Q21 - Q30,Sí,Sí,Portugal,Probablemente no,Suecia,Cristiano Ronaldo; Kylian Mbappé; Christian Pu...,Una selección nacional,Producto gratis,Sí,Edición Brasil
2,3,2026-04-22,35 - 44 años,Masculino,Alta Verapaz,Alta Verapaz,Estudiante,Varias veces al mes,Kiosco escolar/universitario,Familia,Q51 - Q100,ChocoKick Bites; Fan Chips Jalapeño; Victory P...,Picante Chapín,Familiar,Q16 - Q20,Sí,Sí,España,Probablemente sí,Portugal,Cristiano Ronaldo; Federico Valverde,Un jugador famoso,Descuento directo,No,Edición con tarjetas coleccionables
3,4,2026-01-28,25 - 34 años,Femenino,Guatemala,San Miguel Petapa,Empleado privado,3 a 5 veces por semana,Gasolinera,Solo,Q25 - Q50,Fan Chips Jalapeño; CrunchMax BBQ,Limón,Familiar,Q16 - Q20,Sí,No,Inglaterra,Probablemente no,España,Vinícius Júnior,Premios y sorteos,2x1,Sí,Edición con jugadores famosos
4,5,2026-03-04,25 - 34 años,Femenino,Guatemala,San Miguel Petapa,Estudiante,Varias veces al mes,Tienda de barrio,Amigos,Q51 - Q100,Caramel Goal Popcorn; FutbolMix,Queso,Para compartir entre 2 personas,Q16 - Q20,No,No,España,Tal vez,Qatar,Kylian Mbappé,Un jugador famoso,Tarjetas coleccionables,No,Edición Brasil

## Paso 4. Exploración y diagnóstico de calidad

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EncuestaID                    2500 non-null   int64
 1   FechaEncuesta                 2500 non-null   str
 2   RangoEdad                     2500 non-null   str
 3   Genero                        2500 non-null   str
 4   Departamento                  2500 non-null   str
 5   Municipio                     2438 non-null   str
 6   Ocupacion                     2463 non-null   str
 7   FrecuenciaConsumoSnacks       2500 non-null   str
 8   LugarCompraSnacks             2470 non-null   str
 9   ConQuienVePartidos            2500 non-null   str
 10  GastoSnacksPartido            2500 non-null   str
 11  SnacksSeleccionados           2500 non-null   str
 12  SaborPreferido                2475 non-null   str
 13  PresentacionPreferida         2500 non-null   str
 14  PrecioAdecuado                2475 non-null   str
 15  PagaMasEdicionMundial         2500 non-null   str
 16  PlaneaVerMundial2026          2500 non-null   str
 17  SeleccionApoya                2500 non-null   str
 18  CompraDisenoSeleccion         2500 non-null   str
 19  SeleccionInfluyeCompra        2475 non-null   str
 20  JugadoresInfluyentes          2500 non-null   str
 21  TipoPublicidadAtractiva       2500 non-null   str
 22  PromocionPreferida            2500 non-null   str
 23  CompraTarjetasColeccionables  2500 non-null   str
 24  CampaniaMasProbableCompra     2500 non-null   str
dtypes: int64(1), str(24)
memory usage: 488.4 KB

In [7]:
nulos = df.isnull().sum().reset_index()
nulos.columns = ['Columna', 'Nulos']
nulos['Porcentaje'] = (nulos['Nulos'] / len(df) * 100).round(2)
nulos[nulos['Nulos'] > 0]

                   Columna  Nulos  Porcentaje
5                Municipio     62        2.48
6                Ocupacion     37        1.48
8        LugarCompraSnacks     30        1.20
12          SaborPreferido     25        1.00
14          PrecioAdecuado     25        1.00
19  SeleccionInfluyeCompra     25        1.00

In [8]:
print('Registros duplicados:', df.duplicated().sum())
print('EncuestaID duplicados:', df['EncuestaID'].duplicated().sum())

Registros duplicados: 12
EncuestaID duplicados: 25

## Paso 5. Limpieza de datos

In [10]:
df = df.rename(columns={
    'PrecioAdecuado': 'PrecioIdealSnack',
    'PagaMasEdicionMundial': 'PagariaEdicionEspecial'
})

### 5.1 Corrección de valores nulos

In [11]:
# Secciones 1-3
df['Ocupacion']          = df['Ocupacion'].fillna('No Indicado')
df['LugarCompraSnacks']  = df['LugarCompraSnacks'].fillna('No Indicado')
df['SaborPreferido']     = df['SaborPreferido'].fillna('No Indicado')

# Secciones 4-7
df['PrecioIdealSnack']          = df['PrecioIdealSnack'].fillna('No Indicado')
df['TipoPublicidadAtractiva']   = df['TipoPublicidadAtractiva'].fillna('No Indicado')
df['PromocionPreferida']        = df['PromocionPreferida'].fillna('No Indicado')
df['CampaniaMasProbableCompra'] = df['CampaniaMasProbableCompra'].fillna('No Indicado')
df['SeleccionApoya']            = df['SeleccionApoya'].fillna('No Indicado')
df['SeleccionInfluyeCompra']    = df['SeleccionInfluyeCompra'].fillna('No Indicado')

print('Nulos restantes:', df.isnull().sum().sum())

Nulos restantes: 62

In [12]:
df.isnull().sum()[df.isnull().sum() > 0]

Municipio    62
dtype: int64

In [13]:
df['Municipio'] = df['Municipio'].fillna('No Indicado')

In [14]:
print(df.isnull().sum().sum())

0

### 5.2 Normalización de texto

In [15]:
columnas_texto = [
    'RangoEdad', 'Genero', 'Departamento', 'Municipio', 'Ocupacion',
    'FrecuenciaConsumoSnacks', 'LugarCompraSnacks', 'ConQuienVePartidos',
    'GastoSnacksPartido', 'SaborPreferido', 'PresentacionPreferida',
    'PrecioIdealSnack', 'PagariaEdicionEspecial', 'PlaneaVerMundial2026',
    'SeleccionApoya', 'CompraDisenoSeleccion', 'SeleccionInfluyeCompra',
    'TipoPublicidadAtractiva', 'PromocionPreferida',
    'CompraTarjetasColeccionables', 'CampaniaMasProbableCompra'
]

for col in columnas_texto:
    df[col] = df[col].astype(str).str.strip().str.title()

# Campos multi-valor: normalizar separador
for campo in ['SnacksSeleccionados', 'JugadoresInfluyentes']:
    df[campo] = (
        df[campo].astype(str)
        .apply(lambda x: '; '.join([v.strip() for v in x.split(';')]))
    )

print('Normalización completada.')
print('\nValores únicos de SaborPreferido:')
print(sorted(df['SaborPreferido'].unique()))

Normalización completada.

Valores únicos de SaborPreferido:
['Barbacoa', 'Caramelo', 'Chocolate', 'Dulce', 'Jalapeño', 'Limón', 'No Indicado', 'Picante Chapín', 'Queso', 'Salado Tradicional']

### 5.3 Conversión de tipos de datos

In [16]:
df['FechaEncuesta'] = pd.to_datetime(df['FechaEncuesta'])

meses_es = {
    1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril',
    5: 'Mayo', 6: 'Junio', 7: 'Julio', 8: 'Agosto',
    9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'
}
df['FechaEncuesta'] = df['FechaEncuesta'].apply(
    lambda f: f'{f.day:02d} {meses_es[f.month]} {f.year}'
)
df['EncuestaID'] = df['EncuestaID'].astype(int)

print('Conversión de tipos completada.')

Conversión de tipos completada.

### 5.4 Órdenes lógicos para columnas ordinales

In [17]:
orden_edad = [
    'Menos De 18 Años', '18 - 24 Años', '25 - 34 Años',
    '35 - 44 Años', '45 - 54 Años', '55 Años O Mas'
]

orden_gasto = [
    'Menos De Q25', 'Q25 - Q50', 'Q51 - Q100', 'Q101 - Q150', 'Más De Q150'
]

orden_frecuencia = [
    'Rara Vez', 'Varias Veces Al Mes', '1 A 2 Veces Por Semana',
    '3 A 5 Veces Por Semana', 'Todos Los Dias'
]

orden_precio = [
    'Menos De Q10', 'Q10 - Q20', 'Q21 - Q35', 'Q36 - Q50', 'Más De Q50'
]

print('Órdenes definidos correctamente.')

Órdenes definidos correctamente.

## Paso 6. Transformación de datos

### 6.1 Gasto promedio estimado en snacks por partido

In [18]:
valores_gasto = df['GastoSnacksPartido'].unique().tolist()

mapa_gasto = {
    'Menos De Q25': 12.5,
    'Q25 - Q50':    37.5,
    'Q51 - Q100':   75.5,
    'Q101 - Q150': 125.5
}
for v in valores_gasto:
    if v not in mapa_gasto:
        mapa_gasto[v] = 175.0

df['GastoPromedio'] = df['GastoSnacksPartido'].map(mapa_gasto)

print('Cobertura del mapa de gasto:', df['GastoPromedio'].isnull().sum(), 'sin mapear')
print(f'Gasto promedio estimado global: Q{df["GastoPromedio"].mean():,.2f}')

Cobertura del mapa de gasto: 0 sin mapear
Gasto promedio estimado global: Q65.21

### 6.2 Precio promedio ideal estimado por rango

In [19]:
valores_precio = df['PrecioIdealSnack'].unique().tolist()

mapa_precio = {
    'Menos De Q10': 7.5,
    'Q10 - Q20':   15.0,
    'Q21 - Q35':   28.0,
    'Q36 - Q50':   43.0,
}
for v in valores_precio:
    if v not in mapa_precio:
        mapa_precio[v] = 57.5

df['PrecioPromedio'] = df['PrecioIdealSnack'].map(mapa_precio)

print('Cobertura del mapa de precio:', df['PrecioPromedio'].isnull().sum(), 'sin mapear')
print(f'Precio promedio ideal estimado global: Q{df["PrecioPromedio"].mean():,.2f}')

Cobertura del mapa de precio: 0 sin mapear
Precio promedio ideal estimado global: Q53.66

### 6.3 Flag de alta intención de compra ligada al Mundial

In [20]:
df['AltaIntencionCompra'] = (
    (df['PlaneaVerMundial2026'].str.lower().str.contains('sí|si', na=False)) &
    (df['CompraDisenoSeleccion'].str.lower().str.contains('sí|si|probablemente|definitivamente', na=False))
).astype(int)

print(f'Encuestados con alta intención de compra: {df["AltaIntencionCompra"].sum():,}')
print(f'Porcentaje del total: {df["AltaIntencionCompra"].mean()*100:.2f}%')

Encuestados con alta intención de compra: 1,651
Porcentaje del total: 66.04%

## Paso 7. Construcción del Star Schema

### 7.1 dim_encuestado

In [21]:
dim_encuestado = df[[
    'EncuestaID', 'RangoEdad', 'Genero', 'Departamento', 'Municipio', 'Ocupacion'
]].copy()

print('dim_encuestado:', dim_encuestado.shape)
dim_encuestado.head()

dim_encuestado: (2500, 6)

,EncuestaID,RangoEdad,Genero,Departamento,Municipio,Ocupacion
0,1,55 Años O Más,Femenino,Guatemala,Santa Catarina Pinula,Jubilado
1,2,18 - 24 Años,Masculino,Guatemala,Santa Catarina Pinula,Empresario
2,3,35 - 44 Años,Masculino,Alta Verapaz,Alta Verapaz,Estudiante
3,4,25 - 34 Años,Femenino,Guatemala,San Miguel Petapa,Empleado Privado
4,5,25 - 34 Años,Femenino,Guatemala,San Miguel Petapa,Estudiante

### 7.2 dim_producto

In [22]:
dim_producto = df[[
    'EncuestaID', 'SaborPreferido', 'PresentacionPreferida'
]].copy()

print('dim_producto:', dim_producto.shape)
dim_producto.head()

dim_producto: (2500, 3)

   EncuestaID  SaborPreferido            PresentacionPreferida
0           1           Dulce                         Familiar
1           2        Caramelo                         Familiar
2           3  Picante Chapín                         Familiar
3           4           Limón                         Familiar
4           5           Queso  Para Compartir Entre 2 Personas

### 7.3 dim_snacks_detalle

Se desanida `SnacksSeleccionados` (separado por `;`) para obtener una fila por snack,
lo que permite contar menciones individuales correctamente.

In [23]:
dim_snacks_detalle = (
    df[['EncuestaID', 'SnacksSeleccionados']].copy()
    .assign(Snack=lambda d: d['SnacksSeleccionados'].str.split('; '))
    .explode('Snack')
    [['EncuestaID', 'Snack']]
    .assign(Snack=lambda d: d['Snack'].str.strip())
    .reset_index(drop=True)
)

print('dim_snacks_detalle:', dim_snacks_detalle.shape)
print('Snacks únicos:', dim_snacks_detalle['Snack'].nunique())
dim_snacks_detalle.head(8)

dim_snacks_detalle: (5007, 2)
Snacks únicos: 10

   EncuestaID                 Snack
0           1             FutbolMix
1           1   Hot Stadium Peanuts
2           1  Caramel Goal Popcorn
3           2       ChocoKick Bites
4           2         CrunchMax BBQ
5           3       ChocoKick Bites
6           3    Fan Chips Jalapeño
7           3      Victory Pretzels

### 7.4 dim_precio

In [24]:
dim_precio = df[[
    'EncuestaID', 'PrecioIdealSnack', 'PrecioPromedio', 'PagariaEdicionEspecial'
]].copy()

print('dim_precio:', dim_precio.shape)
dim_precio.head()

dim_precio: (2500, 4)

   EncuestaID PrecioIdealSnack  PrecioPromedio PagariaEdicionEspecial
0           1        Q10 - Q15           57.50                     Sí
1           2        Q21 - Q30           57.50                     Sí
2           3        Q16 - Q20           57.50                     Sí
3           4        Q16 - Q20           57.50                     Sí
4           5        Q16 - Q20           57.50                     No

### 7.5 dim_mundial

In [25]:
dim_mundial = df[[
    'EncuestaID', 'PlaneaVerMundial2026', 'SeleccionApoya',
    'CompraDisenoSeleccion', 'SeleccionInfluyeCompra', 'AltaIntencionCompra'
]].copy()

print('dim_mundial:', dim_mundial.shape)
dim_mundial.head()

dim_mundial: (2500, 6)

,EncuestaID,PlaneaVerMundial2026,SeleccionApoya,CompraDisenoSeleccion,SeleccionInfluyeCompra,AltaIntencionCompra
0,1,Sí,Portugal,Probablemente Sí,Portugal,1
1,2,Sí,Portugal,Probablemente No,Suecia,1
2,3,Sí,España,Probablemente Sí,Portugal,1
3,4,No,Inglaterra,Probablemente No,España,0
4,5,No,España,Tal Vez,Qatar,0

### 7.6 dim_jugadores_detalle

Se desanida `JugadoresInfluyentes` (separado por `;`) para obtener una fila por jugador.

In [26]:
dim_jugadores_detalle = (
    df[['EncuestaID', 'JugadoresInfluyentes']].copy()
    .assign(Jugador=lambda d: d['JugadoresInfluyentes'].str.split('; '))
    .explode('Jugador')
    [['EncuestaID', 'Jugador']]
    .assign(Jugador=lambda d: d['Jugador'].str.strip())
    .reset_index(drop=True)
)

# Excluir vacíos y "Ninguno"
dim_jugadores_detalle = dim_jugadores_detalle[
    ~dim_jugadores_detalle['Jugador'].str.lower().isin(['ninguno', 'nan', ''])
].reset_index(drop=True)

print('dim_jugadores_detalle:', dim_jugadores_detalle.shape)
print('Jugadores únicos:', dim_jugadores_detalle['Jugador'].nunique())
dim_jugadores_detalle.head(8)

dim_jugadores_detalle: (4821, 2)
Jugadores únicos: 13

   EncuestaID            Jugador
0           1      Kylian Mbappé
1           1  Cristiano Ronaldo
2           1         Neymar Jr.
3           2  Cristiano Ronaldo
4           2      Kylian Mbappé
5           2  Christian Pulisic
6           3  Cristiano Ronaldo
7           3  Federico Valverde

### 7.7 dim_promociones

In [27]:
dim_promociones = df[[
    'EncuestaID', 'TipoPublicidadAtractiva', 'PromocionPreferida',
    'CompraTarjetasColeccionables', 'CampaniaMasProbableCompra'
]].copy()

print('dim_promociones:', dim_promociones.shape)
dim_promociones.head()

dim_promociones: (2500, 5)

,EncuestaID,TipoPublicidadAtractiva,PromocionPreferida,CompraTarjetasColeccionables,CampaniaMasProbableCompra
0,1,Una Selección Nacional,Sorteo De Viajes,Sí,Edición Francia
1,2,Una Selección Nacional,Producto Gratis,Sí,Edición Brasil
2,3,Un Jugador Famoso,Descuento Directo,No,Edición Con Tarjetas Coleccionables
3,4,Premios Y Sorteos,2X1,Sí,Edición Con Jugadores Famosos
4,5,Un Jugador Famoso,Tarjetas Coleccionables,No,Edición Brasil

### 7.8 fact_encuesta (tabla de hechos unificada)

In [28]:
fact_encuesta = df[[
    'EncuestaID', 'FechaEncuesta',
    'FrecuenciaConsumoSnacks', 'LugarCompraSnacks',
    'ConQuienVePartidos', 'GastoSnacksPartido', 'GastoPromedio',
    'PrecioIdealSnack', 'PrecioPromedio', 'PagariaEdicionEspecial',
    'PlaneaVerMundial2026', 'CompraDisenoSeleccion', 'AltaIntencionCompra'
]].copy()

print('fact_encuesta:', fact_encuesta.shape)
fact_encuesta.head()

fact_encuesta: (2500, 13)

,EncuestaID,FechaEncuesta,FrecuenciaConsumoSnacks,LugarCompraSnacks,ConQuienVePartidos,GastoSnacksPartido,GastoPromedio,PrecioIdealSnack,PrecioPromedio,PagariaEdicionEspecial,PlaneaVerMundial2026,CompraDisenoSeleccion,AltaIntencionCompra
0,1,15 Abril 2026,Varias Veces Al Mes,Aplicación De Delivery,Amigos,Q25 - Q50,37.50,Q10 - Q15,57.50,Sí,Sí,Probablemente Sí,1
1,2,26 Enero 2026,1 A 2 Veces Por Semana,Supermercado,Solo,Q51 - Q100,75.50,Q21 - Q30,57.50,Sí,Sí,Probablemente No,1
2,3,22 Abril 2026,Varias Veces Al Mes,Kiosco Escolar/Universitario,Familia,Q51 - Q100,75.50,Q16 - Q20,57.50,Sí,Sí,Probablemente Sí,1
3,4,28 Enero 2026,3 A 5 Veces Por Semana,Gasolinera,Solo,Q25 - Q50,37.50,Q16 - Q20,57.50,Sí,No,Probablemente No,0
4,5,04 Marzo 2026,Varias Veces Al Mes,Tienda De Barrio,Amigos,Q51 - Q100,75.50,Q16 - Q20,57.50,No,No,Tal Vez,0

## Paso 8. KPIs ejecutivos

In [30]:
total_encuestados        = len(df)
total_departamentos      = df['Departamento'].nunique()
total_municipios         = df['Municipio'].nunique()
gasto_promedio_global    = df['GastoPromedio'].mean()
precio_promedio_global   = df['PrecioPromedio'].mean()
total_menciones_snacks   = len(dim_snacks_detalle)
total_menciones_jugadores= len(dim_jugadores_detalle)
pct_ve_mundial           = (
    df['PlaneaVerMundial2026'].str.lower().str.contains('sí|si', na=False).sum()
    / total_encuestados * 100
)
pct_alta_intencion       = df['AltaIntencionCompra'].mean() * 100

print('════════════════════════════════════════════')
print('  KPIs EJECUTIVOS — ENCUESTA COMPLETA')
print('════════════════════════════════════════════')
print(f'  Total de encuestados:            {total_encuestados:,}')
print(f'  Departamentos cubiertos:         {total_departamentos}')
print(f'  Municipios cubiertos:            {total_municipios}')
print(f'  Gasto promedio por partido:      Q{gasto_promedio_global:,.2f}')
print(f'  Precio ideal promedio estimado:  Q{precio_promedio_global:,.2f}')
print(f'  Total menciones de snacks:       {total_menciones_snacks:,}')
print(f'  Total menciones de jugadores:    {total_menciones_jugadores:,}')
print(f'  Planea ver el Mundial:           {pct_ve_mundial:.1f}%')
print(f'  Alta intención de compra:        {pct_alta_intencion:.1f}%')

════════════════════════════════════════════
  KPIs EJECUTIVOS — ENCUESTA COMPLETA
════════════════════════════════════════════
  Total de encuestados:            2,500
  Departamentos cubiertos:         24
  Municipios cubiertos:            40
  Gasto promedio por partido:      Q65.21
  Precio ideal promedio estimado:  Q53.66
  Total menciones de snacks:       5,007
  Total menciones de jugadores:    4,821
  Planea ver el Mundial:           87.9%
  Alta intención de compra:        66.0%

## Paso 9. Reportes para directivos

### 9.1 Perfil demográfico: distribución por departamento y ocupación

In [31]:
perfil_depto_ocupacion = (
    df.groupby(['Departamento', 'Ocupacion'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['Departamento', 'Encuestados'], ascending=[True, False])
)
perfil_depto_ocupacion['Porcentaje'] = (
    perfil_depto_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Perfil del consumidor por departamento y ocupación:')
perfil_depto_ocupacion.head(20)

Perfil del consumidor por departamento y ocupación:

     Departamento                  Ocupacion  Encuestados  Porcentaje
2    Alta Verapaz           Empleado Privado           15        0.60
5    Alta Verapaz                 Estudiante            8        0.32
7    Alta Verapaz  Profesional Independiente            5        0.20
0    Alta Verapaz                Ama De Casa            4        0.16
4    Alta Verapaz                 Empresario            4        0.16
1    Alta Verapaz                Comerciante            3        0.12
3    Alta Verapaz           Empleado Público            3        0.12
6    Alta Verapaz                       Otro            2        0.08
9    Baja Verapaz                Comerciante           11        0.44
10   Baja Verapaz           Empleado Privado            7        0.28
8    Baja Verapaz                Ama De Casa            5        0.20
13   Baja Verapaz                 Estudiante            5        0.20
15   Baja Verapaz  Profesional Independiente            5        0.20
11   Baja Verapaz           Empleado Público            3        0.12
12   Baja Verapaz                 Empresario            3        0.12
14   Baja Verapaz                No Indicado            1        0.04
18  Chimaltenango           Empleado Privado           47        1.88
21  Chimaltenango                 Estudiante           36        1.44
17  Chimaltenango                Comerciante           18        0.72
19  Chimaltenango           Empleado Público           17        0.68

> **Interpretación:** La tabla muestra la concentración geográfica y ocupacional de la muestra.
> Los departamentos con mayor volumen de respuestas son los mercados prioritarios para la distribución
> de snacks temáticos. La ocupación dominante en cada departamento orienta el tono y canal
> de comunicación a estudiantes y empleados privados responden mejor a promociones digitales y 2x1,
> mientras que profesionales y empresarios prefieren ediciones premium.

### 9.2 Género: distribución global y por perfil demográfico

In [32]:
genero_global = (
    df['Genero'].value_counts(normalize=True)
    .mul(100).round(2).reset_index()
)
genero_global.columns = ['Genero', 'Porcentaje']

print('Género — Porcentaje global:')
print(genero_global.to_string(index=False))

Género — Porcentaje global:
               Genero  Porcentaje
            Masculino       48.60
             Femenino       48.44
Prefiero No Indicarlo        2.96

In [33]:
genero_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'Genero'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
genero_edad_ocupacion['Porcentaje'] = (
    genero_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Género por rango de edad y ocupación:')
genero_edad_ocupacion.head(20)

Género por rango de edad y ocupación:

,RangoEdad,Ocupacion,Genero,Encuestados,Porcentaje
0,18 - 24 Años,Ama De Casa,Femenino,21,0.84
1,18 - 24 Años,Ama De Casa,Masculino,20,0.80
3,18 - 24 Años,Comerciante,Masculino,38,1.52
2,18 - 24 Años,Comerciante,Femenino,33,1.32
4,18 - 24 Años,Empleado Privado,Femenino,105,4.20
5,18 - 24 Años,Empleado Privado,Masculino,83,3.32
6,18 - 24 Años,Empleado Privado,Prefiero No Indicarlo,5,0.20
8,18 - 24 Años,Empleado Público,Masculino,25,1.00
7,18 - 24 Años,Empleado Público,Femenino,20,0.80
9,18 - 24 Años,Empresario,Femenino,22,0.88
10,18 - 24 Años,Empresario,Masculino,21,0.84
11,18 - 24 Años,Empresario,Prefiero No Indicarlo,1,0.04
12,18 - 24 Años,Estudiante,Femenino,46,1.84
13,18 - 24 Años,Estudiante,Masculino,33,1.32
14,18 - 24 Años,Estudiante,Prefiero No Indicarlo,1,0.04
15,18 - 24 Años,Jubilado,Femenino,7,0.28
16,18 - 24 Años,Jubilado,Masculino,4,0.16
17,18 - 24 Años,No Indicado,Femenino,6,0.24
18,18 - 24 Años,No Indicado,Masculino,3,0.12
20,18 - 24 Años,Otro,Masculino,17,0.68

> **Interpretación:** La distribución de género permite segmentar creatividades publicitarias.
> Si el género masculino domina en rangos 25-44, las campañas centradas en jugadores estrella
> (Messi, Mbappé) y ediciones de selecciones tienen mayor retorno en ese segmento.
> Para segmentos con mayor presencia femenina, las propuestas de snacks de sabores dulces
> (Caramel Goal Popcorn, ChocoKick Bites) y presentaciones individuales pueden tener mejorvista para ellas.

### 9.3 Frecuencia de consumo de snacks

In [34]:
frecuencia_rank = (
    df['FrecuenciaConsumoSnacks'].value_counts().reset_index()
)
frecuencia_rank.columns = ['FrecuenciaConsumoSnacks', 'Encuestados']
frecuencia_rank['Porcentaje'] = (
    frecuencia_rank['Encuestados'] / total_encuestados * 100
).round(2)
frecuencia_rank.insert(0, 'Posicion', range(1, len(frecuencia_rank) + 1))

print('Ranking de frecuencia de consumo (global):')
print(frecuencia_rank.to_string(index=False))

Ranking de frecuencia de consumo (global):
 Posicion FrecuenciaConsumoSnacks  Encuestados  Porcentaje
        1  1 A 2 Veces Por Semana          698       27.92
        2  3 A 5 Veces Por Semana          674       26.96
        3     Varias Veces Al Mes          493       19.72
        4          Todos Los Días          466       18.64
        5                Rara Vez          169        6.76

In [35]:
frecuencia_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'FrecuenciaConsumoSnacks'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
frecuencia_edad_ocupacion['Porcentaje'] = (
    frecuencia_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Frecuencia de consumo por rango de edad y ocupación:')
frecuencia_edad_ocupacion.head(20)

Frecuencia de consumo por rango de edad y ocupación:

,RangoEdad,Ocupacion,FrecuenciaConsumoSnacks,Encuestados,Porcentaje
1,18 - 24 Años,Ama De Casa,3 A 5 Veces Por Semana,13,0.52
0,18 - 24 Años,Ama De Casa,1 A 2 Veces Por Semana,12,0.48
3,18 - 24 Años,Ama De Casa,Todos Los Días,8,0.32
4,18 - 24 Años,Ama De Casa,Varias Veces Al Mes,7,0.28
2,18 - 24 Años,Ama De Casa,Rara Vez,1,0.04
6,18 - 24 Años,Comerciante,3 A 5 Veces Por Semana,24,0.96
5,18 - 24 Años,Comerciante,1 A 2 Veces Por Semana,22,0.88
8,18 - 24 Años,Comerciante,Todos Los Días,10,0.40
9,18 - 24 Años,Comerciante,Varias Veces Al Mes,10,0.40
7,18 - 24 Años,Comerciante,Rara Vez,5,0.20
10,18 - 24 Años,Empleado Privado,1 A 2 Veces Por Semana,57,2.28
11,18 - 24 Años,Empleado Privado,3 A 5 Veces Por Semana,45,1.80
14,18 - 24 Años,Empleado Privado,Varias Veces Al Mes,45,1.80
13,18 - 24 Años,Empleado Privado,Todos Los Días,29,1.16
12,18 - 24 Años,Empleado Privado,Rara Vez,17,0.68
16,18 - 24 Años,Empleado Público,3 A 5 Veces Por Semana,12,0.48
18,18 - 24 Años,Empleado Público,Todos Los Días,11,0.44
19,18 - 24 Años,Empleado Público,Varias Veces Al Mes,9,0.36
15,18 - 24 Años,Empleado Público,1 A 2 Veces Por Semana,7,0.28
17,18 - 24 Años,Empleado Público,Rara Vez,6,0.24

> **Interpretación:** La frecuencia de consumo define la intensidad de la oportunidad de negocio.
> Consumidores que compran snacks 3-5 veces por semana o diariamente son el centro del volumen de ventas;
> activarlos con tarjetas coleccionables del Mundial o empaques de jugadores como Messi o Mbappé
> genera compras recurrentes. Los consumidores ocasionales ("Rara Vez") pueden ser manejados
> con ediciones especiales de selecciones y promociones de tiempo limitado durante los partidos.

### 9.4 Canal de compra: ranking y top 3

In [36]:
lugar_rank = (
    df['LugarCompraSnacks'].value_counts().reset_index()
)
lugar_rank.columns = ['LugarCompraSnacks', 'Encuestados']
lugar_rank['Porcentaje'] = (
    lugar_rank['Encuestados'] / total_encuestados * 100
).round(2)
lugar_rank.insert(0, 'Posicion', range(1, len(lugar_rank) + 1))

print('Ranking de canal de compra (global):')
print(lugar_rank.to_string(index=False))

Ranking de canal de compra (global):
 Posicion            LugarCompraSnacks  Encuestados  Porcentaje
        1             Tienda De Barrio          776       31.04
        2                 Supermercado          770       30.80
        3                   Gasolinera          362       14.48
        4       Aplicación De Delivery          239        9.56
        5 Kiosco Escolar/Universitario          194        7.76
        6                         Otro          129        5.16
        7                  No Indicado           30        1.20

In [37]:
top3_lugar = lugar_rank.head(3)[['Posicion', 'LugarCompraSnacks', 'Porcentaje']]
print('Top 3 canales de compra:')
print(top3_lugar.to_string(index=False))

Top 3 canales de compra:
 Posicion LugarCompraSnacks  Porcentaje
        1  Tienda De Barrio       31.04
        2      Supermercado       30.80
        3        Gasolinera       14.48

In [38]:
lugar_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'LugarCompraSnacks'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
lugar_edad_ocupacion['Porcentaje'] = (
    lugar_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Canal de compra por rango de edad y ocupación:')
lugar_edad_ocupacion.head(20)

Canal de compra por rango de edad y ocupación:

,RangoEdad,Ocupacion,LugarCompraSnacks,Encuestados,Porcentaje
4,18 - 24 Años,Ama De Casa,Supermercado,17,0.68
5,18 - 24 Años,Ama De Casa,Tienda De Barrio,11,0.44
1,18 - 24 Años,Ama De Casa,Gasolinera,6,0.24
2,18 - 24 Años,Ama De Casa,Kiosco Escolar/Universitario,4,0.16
0,18 - 24 Años,Ama De Casa,Aplicación De Delivery,2,0.08
3,18 - 24 Años,Ama De Casa,No Indicado,1,0.04
11,18 - 24 Años,Comerciante,Tienda De Barrio,25,1.00
10,18 - 24 Años,Comerciante,Supermercado,23,0.92
6,18 - 24 Años,Comerciante,Aplicación De Delivery,9,0.36
7,18 - 24 Años,Comerciante,Gasolinera,7,0.28
9,18 - 24 Años,Comerciante,Otro,4,0.16
8,18 - 24 Años,Comerciante,Kiosco Escolar/Universitario,3,0.12
17,18 - 24 Años,Empleado Privado,Supermercado,68,2.72
18,18 - 24 Años,Empleado Privado,Tienda De Barrio,64,2.56
13,18 - 24 Años,Empleado Privado,Gasolinera,29,1.16
12,18 - 24 Años,Empleado Privado,Aplicación De Delivery,17,0.68
16,18 - 24 Años,Empleado Privado,Otro,9,0.36
14,18 - 24 Años,Empleado Privado,Kiosco Escolar/Universitario,5,0.20
15,18 - 24 Años,Empleado Privado,No Indicado,1,0.04
24,18 - 24 Años,Empleado Público,Tienda De Barrio,19,0.76

> **Interpretación:** Los canales con mayor concentración son el punto de activación 
> para el material POP temático del Mundial. Si supermercados y tiendas de conveniencia lideran,
> las exhibiciones especiales con diseños de selecciones (Brasil, Argentina) y displays de jugadores
> estrella maximizan la visibilidad en el momento de compra por impulso.
> Los canales digitales o delivery son secundarios pero crecientes en rangos 18-34 años.

### 9.5 Compañía al ver los partidos

In [39]:
compania_rank = (
    df['ConQuienVePartidos'].value_counts().reset_index()
)
compania_rank.columns = ['ConQuienVePartidos', 'Encuestados']
compania_rank['Porcentaje'] = (
    compania_rank['Encuestados'] / total_encuestados * 100
).round(2)
compania_rank.insert(0, 'Posicion', range(1, len(compania_rank) + 1))

print('Ranking — con quién ve los partidos (global):')
print(compania_rank.to_string(index=False))

Ranking — con quién ve los partidos (global):
 Posicion    ConQuienVePartidos  Encuestados  Porcentaje
        1               Familia         1030       41.20
        2                Amigos          910       36.40
        3 Compañeros De Trabajo          236        9.44
        4                  Solo          215        8.60
        5                  Otro          109        4.36

In [40]:
compania_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'ConQuienVePartidos'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
compania_edad_ocupacion['Porcentaje'] = (
    compania_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Compañía al ver los partidos por rango de edad y ocupación:')
compania_edad_ocupacion.head(20)

Compañía al ver los partidos por rango de edad y ocupación:

,RangoEdad,Ocupacion,ConQuienVePartidos,Encuestados,Porcentaje
0,18 - 24 Años,Ama De Casa,Amigos,15,0.60
2,18 - 24 Años,Ama De Casa,Familia,14,0.56
4,18 - 24 Años,Ama De Casa,Solo,6,0.24
3,18 - 24 Años,Ama De Casa,Otro,4,0.16
1,18 - 24 Años,Ama De Casa,Compañeros De Trabajo,2,0.08
7,18 - 24 Años,Comerciante,Familia,32,1.28
5,18 - 24 Años,Comerciante,Amigos,20,0.80
9,18 - 24 Años,Comerciante,Solo,10,0.40
6,18 - 24 Años,Comerciante,Compañeros De Trabajo,5,0.20
8,18 - 24 Años,Comerciante,Otro,4,0.16
12,18 - 24 Años,Empleado Privado,Familia,77,3.08
10,18 - 24 Años,Empleado Privado,Amigos,76,3.04
11,18 - 24 Años,Empleado Privado,Compañeros De Trabajo,18,0.72
14,18 - 24 Años,Empleado Privado,Solo,18,0.72
13,18 - 24 Años,Empleado Privado,Otro,4,0.16
17,18 - 24 Años,Empleado Público,Familia,15,0.60
15,18 - 24 Años,Empleado Público,Amigos,12,0.48
16,18 - 24 Años,Empleado Público,Compañeros De Trabajo,8,0.32
19,18 - 24 Años,Empleado Público,Solo,6,0.24
18,18 - 24 Años,Empleado Público,Otro,4,0.16

> **Interpretación:** Ver los partidos en grupo (familia o amigos) incrementa el ticket promedio
> de snacks porque se compran en mayor cantidad. Las presentaciones familiares o multipack
> son más atractivas para quienes ven los partidos acompañados. Las promociones tipo "lleva 2 paga 1"
> o combos de selección son más efectivas en este segmento. Quienes ven solos priorizan
> porciones individuales y precio unitario bajo.

### 9.6 Presupuesto destinado a snacks por partido

In [41]:
gasto_rank = (
    df['GastoSnacksPartido'].value_counts().reset_index()
)
gasto_rank.columns = ['GastoSnacksPartido', 'Encuestados']
gasto_rank['Porcentaje'] = (
    gasto_rank['Encuestados'] / total_encuestados * 100
).round(2)
gasto_rank.insert(0, 'Posicion', range(1, len(gasto_rank) + 1))

print('Ranking de presupuesto por partido (global):')
print(gasto_rank.to_string(index=False))
print()
print(f'Gasto promedio estimado global: Q{df["GastoPromedio"].mean():,.2f}')

Ranking de presupuesto por partido (global):
 Posicion GastoSnacksPartido  Encuestados  Porcentaje
        1          Q25 - Q50          867       34.68
        2         Q51 - Q100          736       29.44
        3       Menos De Q25          404       16.16
        4        Q101 - Q150          331       13.24
        5        Más De Q150          162        6.48

Gasto promedio estimado global: Q65.21

In [ ]:
gasto_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'GastoSnacksPartido'])
    .agg(
        Encuestados=('EncuestaID', 'count'),
        GastoPromedioEstimado=('GastoPromedio', 'mean')
    )
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
gasto_edad_ocupacion['Porcentaje'] = (
    gasto_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)
gasto_edad_ocupacion['GastoPromedioEstimado'] = (
    gasto_edad_ocupacion['GastoPromedioEstimado'].round(2)
)

print('Presupuesto por rango de edad y ocupación:')
gasto_edad_ocupacion.head(20)

> **Interpretación:** El rango de gasto dominante define el precio óptimo del empaque.
> Si la mayoría se concentra en Q25-Q50, los snacks temáticos del Mundial deberían posicionarse
> en ese rango para maximizar conversión. Los segmentos de mayor gasto (Q101+) son los candidatos
> ideales para ediciones premium coleccionables con diseño de selecciones o jugadores estrella.
> El gasto promedio estimado es la métrica para proyectar ingresos por partido transmitido.

### 9.7 Snacks favoritos: top 10 y top 3

In [42]:
snack_rank = (
    dim_snacks_detalle['Snack'].value_counts().reset_index()
)
snack_rank.columns = ['Snack', 'Menciones']
snack_rank['PorcentajeDeEncuestados'] = (
    snack_rank['Menciones'] / total_encuestados * 100
).round(2)
snack_rank.insert(0, 'Posicion', range(1, len(snack_rank) + 1))

print('Ranking de snacks favoritos (top 10):')
print(snack_rank.head(10).to_string(index=False))

Ranking de snacks favoritos (top 10):
 Posicion                     Snack  Menciones  PorcentajeDeEncuestados
        1 Mundialitos Queso Picante        692                    27.68
        2             CrunchMax BBQ        679                    27.16
        3        Gol Nachos Supreme        643                    25.72
        4        Fan Chips Jalapeño        580                    23.20
        5                 FutbolMix        574                    22.96
        6      Caramel Goal Popcorn        453                    18.12
        7           ChocoKick Bites        438                    17.52
        8       Hot Stadium Peanuts        420                    16.80
        9     Energy Crunch Protein        285                    11.40
       10          Victory Pretzels        243                     9.72

In [43]:
top3_snacks = snack_rank.head(3)[['Posicion', 'Snack', 'PorcentajeDeEncuestados']]
print('Top 3 snacks favoritos:')
print(top3_snacks.to_string(index=False))

Top 3 snacks favoritos:
 Posicion                     Snack  PorcentajeDeEncuestados
        1 Mundialitos Queso Picante                    27.68
        2             CrunchMax BBQ                    27.16
        3        Gol Nachos Supreme                    25.72

In [44]:
snack_con_perfil = pd.merge(
    dim_snacks_detalle,
    dim_encuestado[['EncuestaID', 'RangoEdad', 'Ocupacion']],
    on='EncuestaID', how='left'
)
snack_edad_ocupacion = (
    snack_con_perfil
    .groupby(['RangoEdad', 'Ocupacion', 'Snack'])
    .agg(Menciones=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Menciones'], ascending=[True, True, False])
)
snack_edad_ocupacion['PorcentajeDeEncuestados'] = (
    snack_edad_ocupacion['Menciones'] / total_encuestados * 100
).round(2)

print('Snacks favoritos por rango de edad y ocupación:')
snack_edad_ocupacion.head(20)

Snacks favoritos por rango de edad y ocupación:

,RangoEdad,Ocupacion,Snack,Menciones,PorcentajeDeEncuestados
0,18 - 24 Años,Ama De Casa,Caramel Goal Popcorn,13,0.52
6,18 - 24 Años,Ama De Casa,Gol Nachos Supreme,13,0.52
5,18 - 24 Años,Ama De Casa,FutbolMix,12,0.48
1,18 - 24 Años,Ama De Casa,ChocoKick Bites,10,0.40
3,18 - 24 Años,Ama De Casa,Energy Crunch Protein,9,0.36
7,18 - 24 Años,Ama De Casa,Hot Stadium Peanuts,9,0.36
8,18 - 24 Años,Ama De Casa,Mundialitos Queso Picante,9,0.36
2,18 - 24 Años,Ama De Casa,CrunchMax BBQ,7,0.28
4,18 - 24 Años,Ama De Casa,Fan Chips Jalapeño,6,0.24
15,18 - 24 Años,Comerciante,Gol Nachos Supreme,21,0.84
17,18 - 24 Años,Comerciante,Mundialitos Queso Picante,19,0.76
11,18 - 24 Años,Comerciante,CrunchMax BBQ,17,0.68
14,18 - 24 Años,Comerciante,FutbolMix,17,0.68
13,18 - 24 Años,Comerciante,Fan Chips Jalapeño,12,0.48
10,18 - 24 Años,Comerciante,ChocoKick Bites,10,0.40
18,18 - 24 Años,Comerciante,Victory Pretzels,9,0.36
16,18 - 24 Años,Comerciante,Hot Stadium Peanuts,8,0.32
9,18 - 24 Años,Comerciante,Caramel Goal Popcorn,6,0.24
12,18 - 24 Años,Comerciante,Energy Crunch Protein,6,0.24
25,18 - 24 Años,Empleado Privado,Gol Nachos Supreme,65,2.60

> **Interpretación:** El snack #1 del ranking es el producto ancla de la campaña del Mundial.
> Su empaque debería ser el primero en recibir el diseño temático de la selección más apoyada
> (ver reporte 9.11) o la imagen del jugador más influyente (ver reporte 9.13).
> El top 3 concentra la mayor parte de las menciones y representa el portafolio mínimo
> a activar con la campaña FIFA 2026. Los snacks fuera del top 5 pueden beneficiarse
> de promociones de "prueba" vinculadas a partidos específicos.

### 9.8 Sabor preferido

In [45]:
sabor_rank = (
    df['SaborPreferido'].value_counts().reset_index()
)
sabor_rank.columns = ['SaborPreferido', 'Encuestados']
sabor_rank['Porcentaje'] = (
    sabor_rank['Encuestados'] / total_encuestados * 100
).round(2)
sabor_rank.insert(0, 'Posicion', range(1, len(sabor_rank) + 1))

print('Ranking de sabor preferido (global):')
print(sabor_rank.to_string(index=False))

Ranking de sabor preferido (global):
 Posicion     SaborPreferido  Encuestados  Porcentaje
        1              Queso          431       17.24
        2     Picante Chapín          419       16.76
        3           Barbacoa          378       15.12
        4           Jalapeño          309       12.36
        5              Limón          278       11.12
        6          Chocolate          210        8.40
        7 Salado Tradicional          195        7.80
        8              Dulce          142        5.68
        9           Caramelo          113        4.52
       10        No Indicado           25        1.00

In [46]:
sabor_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'SaborPreferido'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
sabor_edad_ocupacion['Porcentaje'] = (
    sabor_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Sabor preferido por rango de edad y ocupación:')
sabor_edad_ocupacion.head(20)

Sabor preferido por rango de edad y ocupación:

,RangoEdad,Ocupacion,SaborPreferido,Encuestados,Porcentaje
0,18 - 24 Años,Ama De Casa,Barbacoa,8,0.32
4,18 - 24 Años,Ama De Casa,Jalapeño,8,0.32
7,18 - 24 Años,Ama De Casa,Queso,8,0.32
6,18 - 24 Años,Ama De Casa,Picante Chapín,6,0.24
2,18 - 24 Años,Ama De Casa,Chocolate,5,0.20
8,18 - 24 Años,Ama De Casa,Salado Tradicional,3,0.12
1,18 - 24 Años,Ama De Casa,Caramelo,1,0.04
3,18 - 24 Años,Ama De Casa,Dulce,1,0.04
5,18 - 24 Años,Ama De Casa,Limón,1,0.04
16,18 - 24 Años,Comerciante,Queso,13,0.52
9,18 - 24 Años,Comerciante,Barbacoa,11,0.44
15,18 - 24 Años,Comerciante,Picante Chapín,10,0.40
11,18 - 24 Años,Comerciante,Chocolate,8,0.32
13,18 - 24 Años,Comerciante,Jalapeño,8,0.32
14,18 - 24 Años,Comerciante,Limón,7,0.28
17,18 - 24 Años,Comerciante,Salado Tradicional,7,0.28
10,18 - 24 Años,Comerciante,Caramelo,5,0.20
12,18 - 24 Años,Comerciante,Dulce,2,0.08
22,18 - 24 Años,Empleado Privado,Jalapeño,35,1.40
25,18 - 24 Años,Empleado Privado,Picante Chapín,33,1.32

> **Interpretación:** El sabor dominante define la prioridad de producción para la edición Mundial.
> Si el picante o BBQ lidera, los snacks con esos sabores deberían ser los primeros en adoptar
> el empaque temático. El sabor es también un eje de segmentación: jóvenes (18-24) típicamente
> prefieren sabores intensos y picantes, mientras adultos (35+) pueden inclinarse hacia
> sabores más clásicos. Cruzar el sabor líder con el snack líder del reporte 9.7
> da el producto exacto a priorizar en la campaña.

### 9.9 Presentación preferida del producto

In [47]:
presentacion_rank = (
    df['PresentacionPreferida'].value_counts().reset_index()
)
presentacion_rank.columns = ['PresentacionPreferida', 'Encuestados']
presentacion_rank['Porcentaje'] = (
    presentacion_rank['Encuestados'] / total_encuestados * 100
).round(2)
presentacion_rank.insert(0, 'Posicion', range(1, len(presentacion_rank) + 1))

print('Ranking de presentación preferida (global):')
print(presentacion_rank.to_string(index=False))

Ranking de presentación preferida (global):
 Posicion           PresentacionPreferida  Encuestados  Porcentaje
        1                        Familiar          857       34.28
        2 Para Compartir Entre 2 Personas          639       25.56
        3                      Individual          577       23.08
        4         Tamaño Fiesta O Reunión          427       17.08

In [48]:
presentacion_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'PresentacionPreferida'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
presentacion_edad_ocupacion['Porcentaje'] = (
    presentacion_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Presentación preferida por rango de edad y ocupación:')
presentacion_edad_ocupacion.head(20)

Presentación preferida por rango de edad y ocupación:

,RangoEdad,Ocupacion,PresentacionPreferida,Encuestados,Porcentaje
2,18 - 24 Años,Ama De Casa,Para Compartir Entre 2 Personas,18,0.72
1,18 - 24 Años,Ama De Casa,Individual,11,0.44
0,18 - 24 Años,Ama De Casa,Familiar,9,0.36
3,18 - 24 Años,Ama De Casa,Tamaño Fiesta O Reunión,3,0.12
4,18 - 24 Años,Comerciante,Familiar,26,1.04
5,18 - 24 Años,Comerciante,Individual,16,0.64
7,18 - 24 Años,Comerciante,Tamaño Fiesta O Reunión,15,0.60
6,18 - 24 Años,Comerciante,Para Compartir Entre 2 Personas,14,0.56
8,18 - 24 Años,Empleado Privado,Familiar,55,2.20
9,18 - 24 Años,Empleado Privado,Individual,54,2.16
10,18 - 24 Años,Empleado Privado,Para Compartir Entre 2 Personas,49,1.96
11,18 - 24 Años,Empleado Privado,Tamaño Fiesta O Reunión,35,1.40
12,18 - 24 Años,Empleado Público,Familiar,15,0.60
13,18 - 24 Años,Empleado Público,Individual,14,0.56
14,18 - 24 Años,Empleado Público,Para Compartir Entre 2 Personas,9,0.36
15,18 - 24 Años,Empleado Público,Tamaño Fiesta O Reunión,7,0.28
16,18 - 24 Años,Empresario,Familiar,14,0.56
17,18 - 24 Años,Empresario,Individual,12,0.48
18,18 - 24 Años,Empresario,Para Compartir Entre 2 Personas,9,0.36
19,18 - 24 Años,Empresario,Tamaño Fiesta O Reunión,9,0.36

> **Interpretación:** La presentación preferida impacta directamente en el SKU a producir
> para la campaña del Mundial. Si el bolsón mediano lidera, ese formato debería recibir
> el diseño de selección o jugador. Las presentaciones individuales son ideales para
> degustaciones en puntos de venta y partidos en grupo pequeño, mientras que los formatos
> familiares o multipack aplican para audiencias que ven los partidos con familia o amigos
> (cruzar con reporte 9.5 para confirmar la oportunidad).

### 9.10 Precio ideal para un snack temático del Mundial

In [49]:
precio_rank = (
    df['PrecioIdealSnack'].value_counts().reset_index()
)
precio_rank.columns = ['PrecioIdealSnack', 'Encuestados']
precio_rank['Porcentaje'] = (
    precio_rank['Encuestados'] / total_encuestados * 100
).round(2)
precio_rank.insert(0, 'Posicion', range(1, len(precio_rank) + 1))

print('Ranking de precio ideal (global):')
print(precio_rank.to_string(index=False))
print()
print(f'Precio promedio ideal estimado global: Q{df["PrecioPromedio"].mean():,.2f}')

Ranking de precio ideal (global):
 Posicion PrecioIdealSnack  Encuestados  Porcentaje
        1        Q16 - Q20          885       35.40
        2        Q10 - Q15          738       29.52
        3        Q21 - Q30          520       20.80
        4     Menos De Q10          192        7.68
        5       Más De Q30          140        5.60
        6      No Indicado           25        1.00

Precio promedio ideal estimado global: Q53.66

In [53]:
precio_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'PrecioIdealSnack'])
      .agg(
          Encuestados=('EncuestaID', 'count')
      )
      .reset_index()
      .sort_values(
          ['RangoEdad', 'Ocupacion', 'Encuestados'],
          ascending=[True, True, False]
      )
)

precio_edad_ocupacion['Porcentaje'] = (
    precio_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

precio_edad_ocupacion.head(20)

       RangoEdad         Ocupacion PrecioIdealSnack  Encuestados  Porcentaje
3   18 - 24 Años       Ama De Casa        Q16 - Q20           11        0.44
2   18 - 24 Años       Ama De Casa        Q10 - Q15           10        0.40
4   18 - 24 Años       Ama De Casa        Q21 - Q30            8        0.32
0   18 - 24 Años       Ama De Casa     Menos De Q10            7        0.28
1   18 - 24 Años       Ama De Casa       Más De Q30            5        0.20
7   18 - 24 Años       Comerciante        Q10 - Q15           24        0.96
8   18 - 24 Años       Comerciante        Q16 - Q20           23        0.92
9   18 - 24 Años       Comerciante        Q21 - Q30           12        0.48
5   18 - 24 Años       Comerciante     Menos De Q10           10        0.40
6   18 - 24 Años       Comerciante       Más De Q30            2        0.08
12  18 - 24 Años  Empleado Privado        Q10 - Q15           71        2.84
13  18 - 24 Años  Empleado Privado        Q16 - Q20           63        2.52
14  18 - 24 Años  Empleado Privado        Q21 - Q30           33        1.32
10  18 - 24 Años  Empleado Privado     Menos De Q10           21        0.84
11  18 - 24 Años  Empleado Privado       Más De Q30            5        0.20
17  18 - 24 Años  Empleado Público        Q10 - Q15           15        0.60
18  18 - 24 Años  Empleado Público        Q16 - Q20           15        0.60
19  18 - 24 Años  Empleado Público        Q21 - Q30           10        0.40
15  18 - 24 Años  Empleado Público     Menos De Q10            4        0.16
16  18 - 24 Años  Empleado Público       Más De Q30            1        0.04

> **Interpretación:** El precio ideal es la de disposición de pago del consumidor guatemalteco
> para un snack temático del Mundial. Fijar el precio de la edición especial dentro del rango
> más votado minimiza la resistencia a la compra. Si el segmento 25-44 años (mayor poder adquisitivo)
> acepta precios más altos, se puede lanzar una versión premium en ese rango
> y una versión accesible en el rango más bajo para estudiantes y jóvenes.

### 9.11 Disposición a pagar más por edición especial del Mundial

In [54]:
edicion_rank = (
    df['PagariaEdicionEspecial'].value_counts().reset_index()
)
edicion_rank.columns = ['PagariaEdicionEspecial', 'Encuestados']
edicion_rank['Porcentaje'] = (
    edicion_rank['Encuestados'] / total_encuestados * 100
).round(2)
edicion_rank.insert(0, 'Posicion', range(1, len(edicion_rank) + 1))

print('Disposición a pagar edición especial (global):')
print(edicion_rank.to_string(index=False))

Disposición a pagar edición especial (global):
 Posicion PagariaEdicionEspecial  Encuestados  Porcentaje
        1                     Sí         1557       62.28
        2                     No          943       37.72

In [55]:
edicion_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'PagariaEdicionEspecial'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
edicion_edad_ocupacion['Porcentaje'] = (
    edicion_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Disposición a pagar edición especial por rango de edad y ocupación:')
edicion_edad_ocupacion.head(20)

Disposición a pagar edición especial por rango de edad y ocupación:

,RangoEdad,Ocupacion,PagariaEdicionEspecial,Encuestados,Porcentaje
1,18 - 24 Años,Ama De Casa,Sí,25,1.00
0,18 - 24 Años,Ama De Casa,No,16,0.64
3,18 - 24 Años,Comerciante,Sí,48,1.92
2,18 - 24 Años,Comerciante,No,23,0.92
5,18 - 24 Años,Empleado Privado,Sí,130,5.20
4,18 - 24 Años,Empleado Privado,No,63,2.52
7,18 - 24 Años,Empleado Público,Sí,28,1.12
6,18 - 24 Años,Empleado Público,No,17,0.68
9,18 - 24 Años,Empresario,Sí,27,1.08
8,18 - 24 Años,Empresario,No,17,0.68
11,18 - 24 Años,Estudiante,Sí,51,2.04
10,18 - 24 Años,Estudiante,No,29,1.16
13,18 - 24 Años,Jubilado,Sí,8,0.32
12,18 - 24 Años,Jubilado,No,3,0.12
15,18 - 24 Años,No Indicado,Sí,5,0.20
14,18 - 24 Años,No Indicado,No,4,0.16
17,18 - 24 Años,Otro,Sí,17,0.68
16,18 - 24 Años,Otro,No,10,0.40
19,18 - 24 Años,Profesional Independiente,Sí,36,1.44
18,18 - 24 Años,Profesional Independiente,No,25,1.00

> **Interpretación:** El porcentaje que responde "Sí" es el tamaño del mercado directo
> para una edición premium FIFA 2026. Combinado con el reporte 9.10, define el precio máximo
> viable. Si más del 50% pagaría más, justifica producir un SKU diferenciado con empaque
> coleccionable de la selección más apoyada (ver 9.12) o del jugador más influyente (ver 9.13),
> con un sobreprecio de 20-30% respecto al precio base.

### 9.12 Intención de seguir el Mundial FIFA 2026

In [56]:
mundial_rank = (
    df['PlaneaVerMundial2026'].value_counts().reset_index()
)
mundial_rank.columns = ['PlaneaVerMundial2026', 'Encuestados']
mundial_rank['Porcentaje'] = (
    mundial_rank['Encuestados'] / total_encuestados * 100
).round(2)
mundial_rank.insert(0, 'Posicion', range(1, len(mundial_rank) + 1))

print('Intención de ver el Mundial FIFA 2026 (global):')
print(mundial_rank.to_string(index=False))

Intención de ver el Mundial FIFA 2026 (global):
 Posicion PlaneaVerMundial2026  Encuestados  Porcentaje
        1                   Sí         2197       87.88
        2                   No          303       12.12

In [57]:
mundial_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'PlaneaVerMundial2026'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
mundial_edad_ocupacion['Porcentaje'] = (
    mundial_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Intención de ver el Mundial por rango de edad y ocupación:')
mundial_edad_ocupacion.head(20)

Intención de ver el Mundial por rango de edad y ocupación:

,RangoEdad,Ocupacion,PlaneaVerMundial2026,Encuestados,Porcentaje
1,18 - 24 Años,Ama De Casa,Sí,39,1.56
0,18 - 24 Años,Ama De Casa,No,2,0.08
3,18 - 24 Años,Comerciante,Sí,60,2.40
2,18 - 24 Años,Comerciante,No,11,0.44
5,18 - 24 Años,Empleado Privado,Sí,170,6.80
4,18 - 24 Años,Empleado Privado,No,23,0.92
7,18 - 24 Años,Empleado Público,Sí,37,1.48
6,18 - 24 Años,Empleado Público,No,8,0.32
9,18 - 24 Años,Empresario,Sí,39,1.56
8,18 - 24 Años,Empresario,No,5,0.20
11,18 - 24 Años,Estudiante,Sí,73,2.92
10,18 - 24 Años,Estudiante,No,7,0.28
12,18 - 24 Años,Jubilado,Sí,11,0.44
14,18 - 24 Años,No Indicado,Sí,8,0.32
13,18 - 24 Años,No Indicado,No,1,0.04
16,18 - 24 Años,Otro,Sí,24,0.96
15,18 - 24 Años,Otro,No,3,0.12
18,18 - 24 Años,Profesional Independiente,Sí,55,2.20
17,18 - 24 Años,Profesional Independiente,No,6,0.24
20,25 - 34 Años,Ama De Casa,Sí,48,1.92

> **Interpretación:** El porcentaje que planea ver el Mundial determina el tamaño del mercado activo
> para la campaña de snacks temáticos. Una intención alta (>80%) valida que el contexto deportivo
> es el momento de consumo correcto para activar la campaña. Los segmentos con menor intención
> de seguir el Mundial son los que menos responderán a empaques de selecciones,
> por lo que en esos perfiles conviene mantener el empaque estándar.

### 9.13 Selección que apoyará principalmente: top 10 y top 3

In [58]:
seleccion_rank = (
    df['SeleccionApoya'].value_counts().reset_index()
)
seleccion_rank.columns = ['SeleccionApoya', 'Encuestados']
seleccion_rank['Porcentaje'] = (
    seleccion_rank['Encuestados'] / total_encuestados * 100
).round(2)
seleccion_rank.insert(0, 'Posicion', range(1, len(seleccion_rank) + 1))

print('Ranking de selecciones apoyadas (top 10):')
print(seleccion_rank.head(10).to_string(index=False))

Ranking de selecciones apoyadas (top 10):
 Posicion SeleccionApoya  Encuestados  Porcentaje
        1      Argentina          437       17.48
        2         Brasil          384       15.36
        3         México          308       12.32
        4        Francia          252       10.08
        5       Portugal          251       10.04
        6         España          181        7.24
        7     Inglaterra          145        5.80
        8 Estados Unidos          112        4.48
        9       Alemania          106        4.24
       10       Colombia           58        2.32

In [59]:
top3_selecciones = seleccion_rank.head(3)[['Posicion', 'SeleccionApoya', 'Porcentaje']]
print('Top 3 selecciones más apoyadas:')
print(top3_selecciones.to_string(index=False))

Top 3 selecciones más apoyadas:
 Posicion SeleccionApoya  Porcentaje
        1      Argentina       17.48
        2         Brasil       15.36
        3         México       12.32

In [60]:
seleccion_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'SeleccionApoya'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
seleccion_edad_ocupacion['Porcentaje'] = (
    seleccion_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Selección apoyada por rango de edad y ocupación:')
seleccion_edad_ocupacion.head(20)

Selección apoyada por rango de edad y ocupación:

       RangoEdad    Ocupacion  SeleccionApoya  Encuestados  Porcentaje
0   18 - 24 Años  Ama De Casa       Argentina           12        0.48
2   18 - 24 Años  Ama De Casa          España            5        0.20
5   18 - 24 Años  Ama De Casa      Inglaterra            5        0.20
6   18 - 24 Años  Ama De Casa          México            5        0.20
1   18 - 24 Años  Ama De Casa          Brasil            4        0.16
3   18 - 24 Años  Ama De Casa  Estados Unidos            4        0.16
4   18 - 24 Años  Ama De Casa         Francia            3        0.12
7   18 - 24 Años  Ama De Casa        Portugal            3        0.12
9   18 - 24 Años  Comerciante       Argentina           13        0.52
20  18 - 24 Años  Comerciante          México           10        0.40
18  18 - 24 Años  Comerciante         Francia            9        0.36
22  18 - 24 Años  Comerciante        Portugal            8        0.32
11  18 - 24 Años  Comerciante          Brasil            7        0.28
16  18 - 24 Años  Comerciante          España            5        0.20
19  18 - 24 Años  Comerciante      Inglaterra            4        0.16
8   18 - 24 Años  Comerciante        Alemania            3        0.12
17  18 - 24 Años  Comerciante  Estados Unidos            2        0.08
23  18 - 24 Años  Comerciante    South Africa            2        0.08
24  18 - 24 Años  Comerciante         Uruguay            2        0.08
10  18 - 24 Años  Comerciante       Australia            1        0.04

> **Interpretación:** La selección #1 en apoyo es la que debe protagonizar el diseño de empaque
> principal de la campaña. Si Brasil lidera, el empaque verde-amarillo con la camiseta canarinha
> es el de mayor potencial de ventas. Si Argentina encabeza, el empaque celeste-blanco con Messi
> como figura central tiene el mayor impacto. El top 3 de selecciones define las 3 variantes
> de empaque coleccionable a producir para el Mundial 2026.
> El cruce por edad y ocupación permite saber qué variante distribuir en qué canal y zona geográfica.

### 9.14 Disposición a comprar snack con diseño de su selección favorita

In [61]:
diseno_rank = (
    df['CompraDisenoSeleccion'].value_counts().reset_index()
)
diseno_rank.columns = ['CompraDisenoSeleccion', 'Encuestados']
diseno_rank['Porcentaje'] = (
    diseno_rank['Encuestados'] / total_encuestados * 100
).round(2)
diseno_rank.insert(0, 'Posicion', range(1, len(diseno_rank) + 1))

print('Disposición a comprar con diseño de selección (global):')
print(diseno_rank.to_string(index=False))

Disposición a comprar con diseño de selección (global):
 Posicion CompraDisenoSeleccion  Encuestados  Porcentaje
        1      Probablemente Sí          799       31.96
        2    Definitivamente Sí          681       27.24
        3               Tal Vez          620       24.80
        4      Probablemente No          245        9.80
        5    Definitivamente No          155        6.20

In [62]:
diseno_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'CompraDisenoSeleccion'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
diseno_edad_ocupacion['Porcentaje'] = (
    diseno_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Compra con diseño de selección por rango de edad y ocupación:')
diseno_edad_ocupacion.head(20)

Compra con diseño de selección por rango de edad y ocupación:

,RangoEdad,Ocupacion,CompraDisenoSeleccion,Encuestados,Porcentaje
3,18 - 24 Años,Ama De Casa,Probablemente Sí,14,0.56
1,18 - 24 Años,Ama De Casa,Definitivamente Sí,13,0.52
4,18 - 24 Años,Ama De Casa,Tal Vez,9,0.36
0,18 - 24 Años,Ama De Casa,Definitivamente No,3,0.12
2,18 - 24 Años,Ama De Casa,Probablemente No,2,0.08
8,18 - 24 Años,Comerciante,Probablemente Sí,27,1.08
6,18 - 24 Años,Comerciante,Definitivamente Sí,17,0.68
9,18 - 24 Años,Comerciante,Tal Vez,14,0.56
7,18 - 24 Años,Comerciante,Probablemente No,7,0.28
5,18 - 24 Años,Comerciante,Definitivamente No,6,0.24
13,18 - 24 Años,Empleado Privado,Probablemente Sí,65,2.60
11,18 - 24 Años,Empleado Privado,Definitivamente Sí,52,2.08
14,18 - 24 Años,Empleado Privado,Tal Vez,39,1.56
12,18 - 24 Años,Empleado Privado,Probablemente No,22,0.88
10,18 - 24 Años,Empleado Privado,Definitivamente No,15,0.60
19,18 - 24 Años,Empleado Público,Tal Vez,16,0.64
16,18 - 24 Años,Empleado Público,Definitivamente Sí,13,0.52
18,18 - 24 Años,Empleado Público,Probablemente Sí,11,0.44
15,18 - 24 Años,Empleado Público,Definitivamente No,4,0.16
17,18 - 24 Años,Empleado Público,Probablemente No,1,0.04

> **Interpretación:** La suma de respuestas positivas (Sí + Probablemente sí + Definitivamente sí)
> representa el porcentaje del mercado que convierte ante un empaque con diseño de selección.
> Este es el indicador de viabilidad directo para la campaña de empaques coleccionables.
> Si supera el 60%, el rediseño del empaque es una inversión con retorno claro.
> Cruzar este dato con la selección #1 del reporte 9.13 confirma qué camiseta poner en la bolsa.

### 9.15 Selección con mayor influencia en la decisión de compra: top 10

In [63]:
influencia_rank = (
    df['SeleccionInfluyeCompra'].value_counts().reset_index()
)
influencia_rank.columns = ['SeleccionInfluyeCompra', 'Encuestados']
influencia_rank['Porcentaje'] = (
    influencia_rank['Encuestados'] / total_encuestados * 100
).round(2)
influencia_rank.insert(0, 'Posicion', range(1, len(influencia_rank) + 1))

print('Ranking de selecciones por influencia en compra (top 10):')
print(influencia_rank.head(10).to_string(index=False))

Ranking de selecciones por influencia en compra (top 10):
 Posicion SeleccionInfluyeCompra  Encuestados  Porcentaje
        1              Argentina          510       20.40
        2                 Brasil          379       15.16
        3                 México          308       12.32
        4               Portugal          239        9.56
        5                Francia          234        9.36
        6                 España          164        6.56
        7             Inglaterra          146        5.84
        8         Estados Unidos           97        3.88
        9               Alemania           81        3.24
       10               Colombia           65        2.60

> **Interpretación:** Este ranking puede diferir del de selección apoyada (9.13):
> un consumidor puede apoyar a Brasil pero ser influenciado a comprar por Argentina
> si Messi aparece en el empaque. La selección con mayor influencia en compra es la que,
> aunque no sea la más querida, tiene el mayor poder de conversión en ventas.
> Es el criterio definitivo para elegir qué selección protagoniza el empaque principal de la campaña.

### 9.16 Jugadores que motivarían la compra: top 10 y top 3

In [64]:
jugador_rank = (
    dim_jugadores_detalle['Jugador'].value_counts().reset_index()
)
jugador_rank.columns = ['Jugador', 'Menciones']
jugador_rank['PorcentajeMenciones'] = (
    jugador_rank['Menciones'] / total_menciones_jugadores * 100
).round(2)
jugador_rank['PorcentajeEncuestados'] = (
    jugador_rank['Menciones'] / total_encuestados * 100
).round(2)
jugador_rank.insert(0, 'Posicion', range(1, len(jugador_rank) + 1))

print('Ranking de jugadores influyentes (top 10):')
print(jugador_rank.head(10).to_string(index=False))

Ranking de jugadores influyentes (top 10):
 Posicion           Jugador  Menciones  PorcentajeMenciones  PorcentajeEncuestados
        1      Lionel Messi        863                17.90                  34.52
        2 Cristiano Ronaldo        815                16.91                  32.60
        3        Neymar Jr.        592                12.28                  23.68
        4     Kylian Mbappé        481                 9.98                  19.24
        5   Vinícius Júnior        457                 9.48                  18.28
        6      Lamine Yamal        343                 7.11                  13.72
        7   Jude Bellingham        315                 6.53                  12.60
        8 Christian Pulisic        197                 4.09                   7.88
        9    Julián Álvarez        172                 3.57                   6.88
       10 Federico Valverde        158                 3.28                   6.32

In [65]:
top3_jugadores = jugador_rank.head(3)[['Posicion', 'Jugador', 'PorcentajeEncuestados']]
print('Top 3 jugadores más influyentes:')
print(top3_jugadores.to_string(index=False))

Top 3 jugadores más influyentes:
 Posicion           Jugador  PorcentajeEncuestados
        1      Lionel Messi                  34.52
        2 Cristiano Ronaldo                  32.60
        3        Neymar Jr.                  23.68

In [66]:
jugador_con_perfil = pd.merge(
    dim_jugadores_detalle,
    dim_encuestado[['EncuestaID', 'RangoEdad', 'Ocupacion']],
    on='EncuestaID', how='left'
)
jugador_edad_ocupacion = (
    jugador_con_perfil
    .groupby(['RangoEdad', 'Ocupacion', 'Jugador'])
    .agg(Menciones=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Menciones'], ascending=[True, True, False])
)
jugador_edad_ocupacion['PorcentajeEncuestados'] = (
    jugador_edad_ocupacion['Menciones'] / total_encuestados * 100
).round(2)

print('Jugadores más influyentes por rango de edad y ocupación:')
jugador_edad_ocupacion.head(20)

Jugadores más influyentes por rango de edad y ocupación:

,RangoEdad,Ocupacion,Jugador,Menciones,PorcentajeEncuestados
2,18 - 24 Años,Ama De Casa,Cristiano Ronaldo,14,0.56
9,18 - 24 Años,Ama De Casa,Lionel Messi,12,0.48
10,18 - 24 Años,Ama De Casa,Neymar Jr.,10,0.40
7,18 - 24 Años,Ama De Casa,Kylian Mbappé,9,0.36
5,18 - 24 Años,Ama De Casa,Jude Bellingham,6,0.24
8,18 - 24 Años,Ama De Casa,Lamine Yamal,6,0.24
0,18 - 24 Años,Ama De Casa,Alphonso Davies,3,0.12
3,18 - 24 Años,Ama De Casa,Federico Valverde,3,0.12
4,18 - 24 Años,Ama De Casa,Harry Kane,3,0.12
1,18 - 24 Años,Ama De Casa,Christian Pulisic,2,0.08
6,18 - 24 Años,Ama De Casa,Julián Álvarez,2,0.08
11,18 - 24 Años,Ama De Casa,Vinícius Júnior,2,0.08
14,18 - 24 Años,Comerciante,Cristiano Ronaldo,26,1.04
21,18 - 24 Años,Comerciante,Lionel Messi,26,1.04
15,18 - 24 Años,Comerciante,Federico Valverde,13,0.52
17,18 - 24 Años,Comerciante,Jude Bellingham,12,0.48
22,18 - 24 Años,Comerciante,Neymar Jr.,12,0.48
24,18 - 24 Años,Comerciante,Vinícius Júnior,11,0.44
20,18 - 24 Años,Comerciante,Lamine Yamal,9,0.36
19,18 - 24 Años,Comerciante,Kylian Mbappé,8,0.32

> **Interpretación:** El jugador #1 del ranking es el embajador natural de la campaña.
> Si Lionel Messi encabeza, su imagen en el empaque del snack más vendido (reporte 9.7)
> con el diseño de Argentina (si Argentina lidera en 9.13) genera la combinación
> de mayor impacto en ventas. Si Cristiano Ronaldo es top 2, se justifica una línea paralela
> para el mercado que apoya a Portugal. El cruce por edad permite saber qué jugador
> resuena con qué generación: Lamine Yamal o Vinícius Jr. pueden ser más efectivos
> en jóvenes de 18-24, mientras Messi y Ronaldo dominan en 25-44 años.

### 9.17 Tipo de publicidad más atractiva

In [67]:
publicidad_rank = (
    df['TipoPublicidadAtractiva'].value_counts().reset_index()
)
publicidad_rank.columns = ['TipoPublicidadAtractiva', 'Encuestados']
publicidad_rank['Porcentaje'] = (
    publicidad_rank['Encuestados'] / total_encuestados * 100
).round(2)
publicidad_rank.insert(0, 'Posicion', range(1, len(publicidad_rank) + 1))

print('Ranking de tipo de publicidad más atractiva (global):')
print(publicidad_rank.to_string(index=False))

Ranking de tipo de publicidad más atractiva (global):
 Posicion  TipoPublicidadAtractiva  Encuestados  Porcentaje
        1        Un Jugador Famoso          737       29.48
        2   Una Selección Nacional          622       24.88
        3        Premios Y Sorteos          474       18.96
        4 Historias De Aficionados          349       13.96
        5                    Humor          318       12.72

In [68]:
publicidad_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'TipoPublicidadAtractiva'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
publicidad_edad_ocupacion['Porcentaje'] = (
    publicidad_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Tipo de publicidad por rango de edad y ocupación:')
publicidad_edad_ocupacion.head(20)

Tipo de publicidad por rango de edad y ocupación:

,RangoEdad,Ocupacion,TipoPublicidadAtractiva,Encuestados,Porcentaje
2,18 - 24 Años,Ama De Casa,Premios Y Sorteos,12,0.48
3,18 - 24 Años,Ama De Casa,Un Jugador Famoso,10,0.40
4,18 - 24 Años,Ama De Casa,Una Selección Nacional,9,0.36
0,18 - 24 Años,Ama De Casa,Historias De Aficionados,8,0.32
1,18 - 24 Años,Ama De Casa,Humor,2,0.08
9,18 - 24 Años,Comerciante,Una Selección Nacional,24,0.96
8,18 - 24 Años,Comerciante,Un Jugador Famoso,15,0.60
6,18 - 24 Años,Comerciante,Humor,13,0.52
7,18 - 24 Años,Comerciante,Premios Y Sorteos,12,0.48
5,18 - 24 Años,Comerciante,Historias De Aficionados,7,0.28
13,18 - 24 Años,Empleado Privado,Un Jugador Famoso,62,2.48
14,18 - 24 Años,Empleado Privado,Una Selección Nacional,50,2.00
12,18 - 24 Años,Empleado Privado,Premios Y Sorteos,32,1.28
11,18 - 24 Años,Empleado Privado,Humor,30,1.20
10,18 - 24 Años,Empleado Privado,Historias De Aficionados,19,0.76
18,18 - 24 Años,Empleado Público,Un Jugador Famoso,12,0.48
15,18 - 24 Años,Empleado Público,Historias De Aficionados,10,0.40
17,18 - 24 Años,Empleado Público,Premios Y Sorteos,10,0.40
19,18 - 24 Años,Empleado Público,Una Selección Nacional,8,0.32
16,18 - 24 Años,Empleado Público,Humor,5,0.20

> **Interpretación:** El formato de publicidad preferido define dónde invertir el presupuesto
> de medios de la campaña del Mundial. Si "Jugador famoso" lidera, el contenido con Messi
> o el jugador top del reporte 9.16 es el formato principal. Si "Selección nacional" ocupa
> el segundo lugar, los creativos con camisetas y partidos son la alternativa de apoyo.
> En segmentos jóvenes (18-24), la publicidad en redes sociales y videos cortos suele
> superar a los formatos tradicionales, lo que define la mezcla de medios por audiencia.

### 9.18 Promoción preferida

In [69]:
promo_rank = (
    df['PromocionPreferida'].value_counts().reset_index()
)
promo_rank.columns = ['PromocionPreferida', 'Encuestados']
promo_rank['Porcentaje'] = (
    promo_rank['Encuestados'] / total_encuestados * 100
).round(2)
promo_rank.insert(0, 'Posicion', range(1, len(promo_rank) + 1))

print('Ranking de promoción preferida (global):')
print(promo_rank.to_string(index=False))

Ranking de promoción preferida (global):
 Posicion      PromocionPreferida  Encuestados  Porcentaje
        1                     2X1          558       22.32
        2       Descuento Directo          545       21.80
        3 Tarjetas Coleccionables          418       16.72
        4         Producto Gratis          314       12.56
        5     Sorteo De Camisetas          278       11.12
        6        Sorteo De Viajes          222        8.88
        7       Sorteo De Balones          165        6.60

In [70]:
promo_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'PromocionPreferida'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
promo_edad_ocupacion['Porcentaje'] = (
    promo_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Promoción preferida por rango de edad y ocupación:')
promo_edad_ocupacion.head(20)

Promoción preferida por rango de edad y ocupación:

,RangoEdad,Ocupacion,PromocionPreferida,Encuestados,Porcentaje
1,18 - 24 Años,Ama De Casa,Descuento Directo,9,0.36
6,18 - 24 Años,Ama De Casa,Tarjetas Coleccionables,9,0.36
5,18 - 24 Años,Ama De Casa,Sorteo De Viajes,7,0.28
0,18 - 24 Años,Ama De Casa,2X1,5,0.20
3,18 - 24 Años,Ama De Casa,Sorteo De Balones,4,0.16
4,18 - 24 Años,Ama De Casa,Sorteo De Camisetas,4,0.16
2,18 - 24 Años,Ama De Casa,Producto Gratis,3,0.12
8,18 - 24 Años,Comerciante,Descuento Directo,22,0.88
7,18 - 24 Años,Comerciante,2X1,13,0.52
13,18 - 24 Años,Comerciante,Tarjetas Coleccionables,12,0.48
11,18 - 24 Años,Comerciante,Sorteo De Camisetas,10,0.40
9,18 - 24 Años,Comerciante,Producto Gratis,8,0.32
10,18 - 24 Años,Comerciante,Sorteo De Balones,3,0.12
12,18 - 24 Años,Comerciante,Sorteo De Viajes,3,0.12
14,18 - 24 Años,Empleado Privado,2X1,55,2.20
15,18 - 24 Años,Empleado Privado,Descuento Directo,42,1.68
16,18 - 24 Años,Empleado Privado,Producto Gratis,26,1.04
20,18 - 24 Años,Empleado Privado,Tarjetas Coleccionables,25,1.00
18,18 - 24 Años,Empleado Privado,Sorteo De Camisetas,24,0.96
17,18 - 24 Años,Empleado Privado,Sorteo De Balones,12,0.48

> **Interpretación:** La promoción favorita es el mecanismo de activación de mayor conversión.
> Si el "2x1" lidera, aplicarlo en los partidos de mayor audiencia (fases eliminatorias,
> final) maximiza el volumen de ventas en los momentos pico. El "descuento directo" funciona
> para atraer consumidores indecisos en punto de venta. Las tarjetas coleccionables
> generan lealtad de largo plazo y compras repetidas, siendo especialmente efectivas
> en niños y jóvenes que coleccionan a sus jugadores favoritos (cruzar con reporte 9.19).

### 9.19 Disposición a comprar snacks con tarjetas coleccionables

In [71]:
tarjetas_rank = (
    df['CompraTarjetasColeccionables'].value_counts().reset_index()
)
tarjetas_rank.columns = ['CompraTarjetasColeccionables', 'Encuestados']
tarjetas_rank['Porcentaje'] = (
    tarjetas_rank['Encuestados'] / total_encuestados * 100
).round(2)
tarjetas_rank.insert(0, 'Posicion', range(1, len(tarjetas_rank) + 1))

print('Disposición a comprar con tarjetas coleccionables (global):')
print(tarjetas_rank.to_string(index=False))

Disposición a comprar con tarjetas coleccionables (global):
 Posicion CompraTarjetasColeccionables  Encuestados  Porcentaje
        1                           Sí         1539       61.56
        2                           No          961       38.44

In [72]:
tarjetas_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'CompraTarjetasColeccionables'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
tarjetas_edad_ocupacion['Porcentaje'] = (
    tarjetas_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Tarjetas coleccionables por rango de edad y ocupación:')
tarjetas_edad_ocupacion.head(20)

Tarjetas coleccionables por rango de edad y ocupación:

,RangoEdad,Ocupacion,CompraTarjetasColeccionables,Encuestados,Porcentaje
1,18 - 24 Años,Ama De Casa,Sí,25,1.00
0,18 - 24 Años,Ama De Casa,No,16,0.64
3,18 - 24 Años,Comerciante,Sí,48,1.92
2,18 - 24 Años,Comerciante,No,23,0.92
5,18 - 24 Años,Empleado Privado,Sí,118,4.72
4,18 - 24 Años,Empleado Privado,No,75,3.00
7,18 - 24 Años,Empleado Público,Sí,25,1.00
6,18 - 24 Años,Empleado Público,No,20,0.80
9,18 - 24 Años,Empresario,Sí,27,1.08
8,18 - 24 Años,Empresario,No,17,0.68
11,18 - 24 Años,Estudiante,Sí,48,1.92
10,18 - 24 Años,Estudiante,No,32,1.28
13,18 - 24 Años,Jubilado,Sí,7,0.28
12,18 - 24 Años,Jubilado,No,4,0.16
15,18 - 24 Años,No Indicado,Sí,7,0.28
14,18 - 24 Años,No Indicado,No,2,0.08
17,18 - 24 Años,Otro,Sí,16,0.64
16,18 - 24 Años,Otro,No,11,0.44
19,18 - 24 Años,Profesional Independiente,Sí,43,1.72
18,18 - 24 Años,Profesional Independiente,No,18,0.72

> **Interpretación:** El porcentaje que respondió "Sí" a comprar snacks con tarjetas coleccionables
> valida una de las mecánicas promocionales de mayor retención de marca en torneos mundiales.
> Las tarjetas con el jugador más influyente del reporte 9.16 (Messi, Ronaldo, Mbappé)
> son las de mayor demanda. Si el "Sí" supera el 55%, la inversión en producción de tarjetas
> está respaldada por datos. El segmento menores de 24 años suele ser el más receptivo
> a esta mecánica, lo que también amplifica el alcance familiar de la compra.

### 9.20 Campaña publicitaria con mayor probabilidad de generar compra

In [73]:
campania_rank = (
    df['CampaniaMasProbableCompra'].value_counts().reset_index()
)
campania_rank.columns = ['CampaniaMasProbableCompra', 'Encuestados']
campania_rank['Porcentaje'] = (
    campania_rank['Encuestados'] / total_encuestados * 100
).round(2)
campania_rank.insert(0, 'Posicion', range(1, len(campania_rank) + 1))

print('Ranking de campañas más motivadoras (global):')
print(campania_rank.to_string(index=False))

Ranking de campañas más motivadoras (global):
 Posicion           CampaniaMasProbableCompra  Encuestados  Porcentaje
        1       Edición Con Jugadores Famosos          421       16.84
        2           Edición Mundial Fifa 2026          399       15.96
        3                   Edición Argentina          390       15.60
        4                      Edición Brasil          364       14.56
        5 Edición Con Tarjetas Coleccionables          312       12.48
        6                     Edición Francia          241        9.64
        7                      Edición España          196        7.84
        8                  Edición Inglaterra          177        7.08

In [74]:
print('Top 5 campañas con mayor probabilidad de generar compra:')
print(campania_rank.head(5).to_string(index=False))

Top 5 campañas con mayor probabilidad de generar compra:
 Posicion           CampaniaMasProbableCompra  Encuestados  Porcentaje
        1       Edición Con Jugadores Famosos          421       16.84
        2           Edición Mundial Fifa 2026          399       15.96
        3                   Edición Argentina          390       15.60
        4                      Edición Brasil          364       14.56
        5 Edición Con Tarjetas Coleccionables          312       12.48

In [75]:
campania_edad_ocupacion = (
    df.groupby(['RangoEdad', 'Ocupacion', 'CampaniaMasProbableCompra'])
    .agg(Encuestados=('EncuestaID', 'count'))
    .reset_index()
    .sort_values(['RangoEdad', 'Ocupacion', 'Encuestados'], ascending=[True, True, False])
)
campania_edad_ocupacion['Porcentaje'] = (
    campania_edad_ocupacion['Encuestados'] / total_encuestados * 100
).round(2)

print('Campaña preferida por rango de edad y ocupación:')
campania_edad_ocupacion.head(20)

Campaña preferida por rango de edad y ocupación:

,RangoEdad,Ocupacion,CampaniaMasProbableCompra,Encuestados,Porcentaje
0,18 - 24 Años,Ama De Casa,Edición Argentina,9,0.36
7,18 - 24 Años,Ama De Casa,Edición Mundial Fifa 2026,8,0.32
1,18 - 24 Años,Ama De Casa,Edición Brasil,6,0.24
2,18 - 24 Años,Ama De Casa,Edición Con Jugadores Famosos,5,0.20
4,18 - 24 Años,Ama De Casa,Edición España,4,0.16
5,18 - 24 Años,Ama De Casa,Edición Francia,4,0.16
3,18 - 24 Años,Ama De Casa,Edición Con Tarjetas Coleccionables,3,0.12
6,18 - 24 Años,Ama De Casa,Edición Inglaterra,2,0.08
11,18 - 24 Años,Comerciante,Edición Con Tarjetas Coleccionables,14,0.56
10,18 - 24 Años,Comerciante,Edición Con Jugadores Famosos,11,0.44
15,18 - 24 Años,Comerciante,Edición Mundial Fifa 2026,11,0.44
8,18 - 24 Años,Comerciante,Edición Argentina,9,0.36
14,18 - 24 Años,Comerciante,Edición Inglaterra,8,0.32
9,18 - 24 Años,Comerciante,Edición Brasil,6,0.24
12,18 - 24 Años,Comerciante,Edición España,6,0.24
13,18 - 24 Años,Comerciante,Edición Francia,6,0.24
16,18 - 24 Años,Empleado Privado,Edición Argentina,34,1.36
23,18 - 24 Años,Empleado Privado,Edición Mundial Fifa 2026,30,1.20
18,18 - 24 Años,Empleado Privado,Edición Con Jugadores Famosos,29,1.16
19,18 - 24 Años,Empleado Privado,Edición Con Tarjetas Coleccionables,24,0.96

> **Interpretación:** La campaña #1 es la narrativa central que debe comunicar la marca
> durante el Mundial 2026. Si "Edición Brasil" o "Edición Mundial FIFA 2026" lidera,
> el concepto del empaque y los creativos deben girar en torno a ese eje.
> Si la campaña con jugador famoso encabeza, confirma que la figura del reporte 9.16
> (Messi, Ronaldo o Mbappé) debe ser el vocero principal.
> El cruce por edad muestra qué mensaje resonar en cada segmento:
> jóvenes suelen preferir campañas de jugadores; adultos, campañas de selecciones clásicas.

## Paso 10. Tablas dinámicas ejecutivas

### 10.1 Top 3 de snacks por departamento

In [76]:
top3_lista = snack_rank.head(3)['Snack'].tolist()
print('Top 3 snacks seleccionados:', top3_lista)

snack_depto = pd.merge(
    dim_snacks_detalle,
    dim_encuestado[['EncuestaID', 'Departamento']],
    on='EncuestaID', how='left'
)

pivot_snack_depto = pd.pivot_table(
    snack_depto[snack_depto['Snack'].isin(top3_lista)],
    values='EncuestaID',
    index='Departamento',
    columns='Snack',
    aggfunc='count',
    fill_value=0
)

print('Menciones del top 3 de snacks por departamento:')
pivot_snack_depto

Top 3 snacks seleccionados: ['Mundialitos Queso Picante', 'CrunchMax BBQ', 'Gol Nachos Supreme']
Menciones del top 3 de snacks por departamento:

Snack           CrunchMax BBQ  Gol Nachos Supreme  Mundialitos Queso Picante
Departamento
Alta Verapaz               10                   7                          7
Baja Verapaz               14                   7                         14
Chimaltenango              47                  45                         39
Chiquimula                 14                  12                         13
El Progreso                17                  13                         15
Escuintla                  47                  47                         60
Guate                       3                   1                          4
Guatemala                 289                 300                        305
Huehuetenango              10                  13                         17
Izabal                     13                   7                          7
Jalapa                     10                  12                         12
Jutiapa                    12                  14                         12
Petén                       9                  12                          8
Quetzaltenango             59                  49                         49
Quiché                      8                  11                         10
Retalhuleu                 17                   7                         16
Sacatepéquez               53                  46                         57
San Marcos                  8                   6                          8
Santa Rosa                 16                  12                          4
Sololá                     13                   7                         17
Suchitepéquez               9                   8                         13
Totonicapán                 6                   8                          2
Xela                        2                   1                          1
Zacapa                      7                  10                         14

> **Interpretación:** Esta tabla cruzada es la guía de distribución por departamento.
> El snack con más menciones en cada fila es el producto ancla de ese mercado.
> Un departamento donde el snack #1 concentra la mayoría de las menciones
> es un mercado consolidado; uno donde hay empate entre productos es un mercado
> competido donde la campaña del Mundial puede definir la preferencia con un empaque atractivo.
> Usar los colores de la selección más apoyada en ese departamento (cruzar con 9.13)
> refuerza la conexión emocional en el punto de venta.

### 10.2 Top 5 de jugadores por selección apoyada

In [77]:
top5_sel_lista = seleccion_rank.head(5)['SeleccionApoya'].tolist()
top5_jug_lista = jugador_rank.head(5)['Jugador'].tolist()

jug_seleccion = pd.merge(
    dim_jugadores_detalle,
    dim_mundial[['EncuestaID', 'SeleccionApoya']],
    on='EncuestaID', how='left'
)

pivot_jug_seleccion = pd.pivot_table(
    jug_seleccion[
        jug_seleccion['SeleccionApoya'].isin(top5_sel_lista) &
        jug_seleccion['Jugador'].isin(top5_jug_lista)
    ],
    values='EncuestaID',
    index='SeleccionApoya',
    columns='Jugador',
    aggfunc='count',
    fill_value=0
)

print('Menciones del top 5 de jugadores por selección apoyada:')
pivot_jug_seleccion

Menciones del top 5 de jugadores por selección apoyada:

Jugador,Cristiano Ronaldo,Kylian Mbappé,Lionel Messi,Neymar Jr.,Vinícius Júnior
SeleccionApoya,,,,,
Argentina,138,88,150,122,86
Brasil,116,64,121,88,76
Francia,95,43,93,65,40
México,93,67,104,72,54
Portugal,102,52,83,60,52

> **Interpretación:** Esta tabla revela la afinidad entre selección y jugador en la mente
> del consumidor guatemalteco. Si los fans de Brasil mencionan masivamente a Vinícius Jr.,
> ese es el duo para el empaque de esa edición. Si los fans de Argentina se inclinan
> por Messi y Julián Álvarez, ambos pueden aparecer en la misma variante coleccionable.
> Las celdas con mayor valor son las combinaciones embajador-selección de mayor impacto comercial
> y deben ser la guía para contratar derechos de imagen y diseñar los empaques coleccionables.

## Paso 11. Exportación para Power BI

In [78]:
# ── Dimensiones y tabla de hechos ──────────────────────────
dim_encuestado.to_csv('dim_encuestado.csv', index=False)
dim_producto.to_csv('dim_producto.csv', index=False)
dim_snacks_detalle.to_csv('dim_snacks_detalle.csv', index=False)
dim_precio.to_csv('dim_precio.csv', index=False)
dim_mundial.to_csv('dim_mundial.csv', index=False)
dim_jugadores_detalle.to_csv('dim_jugadores_detalle.csv', index=False)
dim_promociones.to_csv('dim_promociones.csv', index=False)
fact_encuesta.to_csv('fact_encuesta.csv', index=False)

print('Dimensiones y tabla de hechos exportadas.')

Dimensiones y tabla de hechos exportadas.

In [79]:
# ── Reportes analíticos para directivos ────────────────────
snack_rank.to_csv('reporte_snacks_ranking.csv', index=False)
sabor_rank.to_csv('reporte_sabor_ranking.csv', index=False)
presentacion_rank.to_csv('reporte_presentacion_ranking.csv', index=False)
lugar_rank.to_csv('reporte_lugar_compra_ranking.csv', index=False)
frecuencia_rank.to_csv('reporte_frecuencia_consumo_ranking.csv', index=False)
gasto_rank.to_csv('reporte_presupuesto_ranking.csv', index=False)
precio_rank.to_csv('reporte_precio_ideal_ranking.csv', index=False)
edicion_rank.to_csv('reporte_edicion_especial_ranking.csv', index=False)
seleccion_rank.to_csv('reporte_seleccion_apoyada_ranking.csv', index=False)
influencia_rank.to_csv('reporte_influencia_seleccion_ranking.csv', index=False)
jugador_rank.to_csv('reporte_jugadores_ranking.csv', index=False)
publicidad_rank.to_csv('reporte_publicidad_ranking.csv', index=False)
promo_rank.to_csv('reporte_promocion_ranking.csv', index=False)
tarjetas_rank.to_csv('reporte_tarjetas_coleccionables_ranking.csv', index=False)
campania_rank.to_csv('reporte_campania_ranking.csv', index=False)
perfil_depto_ocupacion.to_csv('reporte_perfil_depto_ocupacion.csv', index=False)
pivot_snack_depto.to_csv('reporte_pivot_snacks_departamento.csv')
pivot_jug_seleccion.to_csv('reporte_pivot_jugadores_seleccion.csv')

print('Reportes analíticos exportados.')
print()
archivos = [
    'dim_encuestado.csv','dim_producto.csv','dim_snacks_detalle.csv',
    'dim_precio.csv','dim_mundial.csv','dim_jugadores_detalle.csv',
    'dim_promociones.csv','fact_encuesta.csv',
    'reporte_snacks_ranking.csv','reporte_sabor_ranking.csv',
    'reporte_presentacion_ranking.csv','reporte_lugar_compra_ranking.csv',
    'reporte_frecuencia_consumo_ranking.csv','reporte_presupuesto_ranking.csv',
    'reporte_precio_ideal_ranking.csv','reporte_edicion_especial_ranking.csv',
    'reporte_seleccion_apoyada_ranking.csv','reporte_influencia_seleccion_ranking.csv',
    'reporte_jugadores_ranking.csv','reporte_publicidad_ranking.csv',
    'reporte_promocion_ranking.csv','reporte_tarjetas_coleccionables_ranking.csv',
    'reporte_campania_ranking.csv','reporte_perfil_depto_ocupacion.csv',
    'reporte_pivot_snacks_departamento.csv','reporte_pivot_jugadores_seleccion.csv'
]
print('Archivos generados:')
for a in archivos:
    print(' -', a)

Reportes analíticos exportados.

Archivos generados:
 - dim_encuestado.csv
 - dim_producto.csv
 - dim_snacks_detalle.csv
 - dim_precio.csv
 - dim_mundial.csv
 - dim_jugadores_detalle.csv
 - dim_promociones.csv
 - fact_encuesta.csv
 - reporte_snacks_ranking.csv
 - reporte_sabor_ranking.csv
 - reporte_presentacion_ranking.csv
 - reporte_lugar_compra_ranking.csv
 - reporte_frecuencia_consumo_ranking.csv
 - reporte_presupuesto_ranking.csv
 - reporte_precio_ideal_ranking.csv
 - reporte_edicion_especial_ranking.csv
 - reporte_seleccion_apoyada_ranking.csv
 - reporte_influencia_seleccion_ranking.csv
 - reporte_jugadores_ranking.csv
 - reporte_publicidad_ranking.csv
 - reporte_promocion_ranking.csv
 - reporte_tarjetas_coleccionables_ranking.csv
 - reporte_campania_ranking.csv
 - reporte_perfil_depto_ocupacion.csv
 - reporte_pivot_snacks_departamento.csv
 - reporte_pivot_jugadores_seleccion.csv

---
## Resumen de archivos generados

### Star Schema — Dimensiones y tabla de hechos

| Archivo | Descripción | Uso en Power BI |
|---|---|---|
| `dim_encuestado.csv` | Perfil demográfico por EncuestaID | Dimensión |
| `dim_producto.csv` | Sabor y presentación por EncuestaID | Dimensión |
| `dim_snacks_detalle.csv` | Una fila por snack seleccionado | Dimensión |
| `dim_precio.csv` | Precio ideal y disposición a pagar | Dimensión |
| `dim_mundial.csv` | Intención de ver el Mundial y selección | Dimensión |
| `dim_jugadores_detalle.csv` | Una fila por jugador influyente | Dimensión |
| `dim_promociones.csv` | Publicidad, promociones y campaña | Dimensión |
| `fact_encuesta.csv` | Hechos de hábitos, gasto y precios | Tabla Fact |

### Reportes analíticos para directivos

| Archivo | Descripción |
|---|---|
| `reporte_snacks_ranking.csv` | Top 10 snacks favoritos |
| `reporte_sabor_ranking.csv` | Ranking de sabores |
| `reporte_presentacion_ranking.csv` | Ranking de presentaciones |
| `reporte_lugar_compra_ranking.csv` | Ranking de canales de compra |
| `reporte_frecuencia_consumo_ranking.csv` | Ranking de frecuencia de consumo |
| `reporte_presupuesto_ranking.csv` | Ranking de gasto por partido |
| `reporte_precio_ideal_ranking.csv` | Ranking de precio ideal |
| `reporte_edicion_especial_ranking.csv` | Disposición a pagar edición especial |
| `reporte_seleccion_apoyada_ranking.csv` | Ranking de selecciones apoyadas |
| `reporte_influencia_seleccion_ranking.csv` | Selecciones por influencia de compra |
| `reporte_jugadores_ranking.csv` | Top jugadores influyentes |
| `reporte_publicidad_ranking.csv` | Ranking de tipos de publicidad |
| `reporte_promocion_ranking.csv` | Ranking de promociones |
| `reporte_tarjetas_coleccionables_ranking.csv` | Disposición a comprar con tarjetas |
| `reporte_campania_ranking.csv` | Ranking de campañas motivadoras |
| `reporte_perfil_depto_ocupacion.csv` | Perfil cruzado departamento-ocupación |
| `reporte_pivot_snacks_departamento.csv` | Top 3 snacks por departamento |
| `reporte_pivot_jugadores_seleccion.csv` | Top jugadores por selección apoyada |

> Todas las tablas se conectan mediante `EncuestaID`.

Para diseñar la campaña de snacks orientada al Mundial FIFA 2026, realizamos una encuesta con 2,500 respuestas a nivel nacional, abarcando múltiples departamentos y municipios de Guatemala. El objetivo fue entender los hábitos de consumo, las preferencias de producto, la afinidad con el fútbol y la disposición de compra del consumidor guatemalteco, para que cada decisión de la campaña esté respaldada por datos reales.

**¿Quién es nuestro consumidor?**

El perfil del encuestado varía entre estudiantes y empleados privados como grupos dominantes, distribuidos principalmente en los departamentos con mayor densidad poblacional. Esta concentración geográfica nos dice dónde enfocar la distribución del producto temático y qué tono de comunicación usar: los estudiantes y jóvenes responden mejor a promociones digitales y mecánicas tipo 2x1, mientras que profesionales y personas de mayor poder adquisitivo son candidatos naturales para ediciones premium coleccionables.

**Consumo y gasto**

La frecuencia de consumo de snacks es alta en una buena parte de la muestra, con consumidores habituales que compran varias veces por semana o incluso a diario. Estos consumidores frecuentes son el corazón de la campaña: activarlos con empaques temáticos del Mundial o tarjetas coleccionables de jugadores genera compras recurrentes. Los consumidores ocasionales, en cambio, pueden capturarse con ediciones especiales de tiempo limitado durante los partidos clave.
En cuanto al gasto por partido, el rango predominante se sitúa entre Q25 y Q50, lo que nos da el precio óptimo de posicionamiento para los snacks temáticos. Los segmentos que gastan más de Q100 son los ideales para una línea premium coleccionable con un sobreprecio de 20 a 30% respecto al precio base estándar.

**Producto:** 

qué snack, qué sabor y en qué presentación
El análisis del top 10 de snacks favoritos nos da el portafolio mínimo a activar con la campaña FIFA 2026. El snack número uno del ranking es el producto ancla: su empaque debe ser el primero en recibir el diseño temático. El top 3 concentra la mayoría de las menciones y representa los tres productos con mayor retorno si se les da visibilidad temática.

**El sabor líder define la prioridad de producción:** 

si el picante o el BBQ encabeza el ranking, esos sabores deben adoptar primero el empaque del Mundial. En cuanto a la presentación, el formato más votado —ya sea bolsón mediano, individual o multipack— es el SKU prioritario para el rediseño. Las presentaciones familiares tienen sentido para quienes ven los partidos en grupo, que según nuestra encuesta representan la mayoría de los consumidores.

**¿Qué selección va en el empaque?**

La selección con más apoyo entre los guatemalteco es la que debe protagonizar el diseño principal. El top 3 de selecciones apoyadas define las tres variantes de empaque coleccionable a producir. Sin embargo, el criterio definitivo no es solo la selección más querida, sino cuál tiene mayor poder de conversión en ventas, lo que puede diferir: un consumidor puede apoyar a Brasil pero ser motivado a comprar si ve a Messi en el empaque. Por eso cruzamos la selección apoyada con la selección que más influye en la decisión de compra para tomar la mejor decisión.

**El jugador embajador**

El jugador número uno del ranking de influencia es el embajador natural de la campaña. Si Messi encabeza, su imagen en el snack más vendido con el diseño de Argentina genera la combinación de mayor impacto en ventas. El cruce por edad nos permite saber qué jugador resuena con cada generación: jugadores como Vinícius Jr. o Lamine Yamal pueden ser más efectivos en el segmento de 18 a 24 años, mientras Messi y Ronaldo dominan en el rango de 25 a 44 años.

**Publicidad y promociones**

El tipo de publicidad más atractiva para el consumidor guatemalteco define dónde invertir el presupuesto de medios. Si el contenido con jugadores famosos lidera, el creativo principal debe girar en torno a la figura embajadora identificada. En segmentos jóvenes, el contenido en redes sociales y videos cortos supera a los formatos tradicionales.

En cuanto a promociones, el 2x1 durante los partidos de mayor audiencia —fases eliminatorias y final— maximiza el volumen de ventas en los momentos pico. Las tarjetas coleccionables, si superan el 55% de interés en nuestra encuesta, están respaldadas por datos para incluirse como mecánica principal, especialmente en el segmento menor de 24 años.

**Conclusión**

La campaña de snacks para el Mundial FIFA 2026 tiene una base sólida en los datos. El producto ancla es el snack líder del ranking, en el sabor dominante, en la presentación más votada, con el diseño de la selección de mayor influencia en compra y la imagen del jugador más mencionado. El precio debe ubicarse en el rango que concentra la mayor disposición de pago, con una variante premium para los segmentos de mayor gasto. Las promociones tipo 2x1 y tarjetas coleccionables son las mecánicas de mayor conversión, y los canales de activación prioritarios son los supermercados y tiendas de conveniencia donde hoy se concentra la compra habitual de snacks.